### ISSUE TITLE
import modules

### ISSUE THREAD

**Issue by wjxjmj** [wenyan-lang/wenyan#100]
有云《九章算經》者，即名曰《算經》
有云《火炬經》者，其有一術曰「梯度下降」，即名曰「降之」

**Comment by BlankRain** [comment]
某有一神 名曰: 九韶,请之
九韶施「大衍求一术」

import sixgod
sixgod.ohmygod()

**Comment by GalAster** [comment]
有书者 名 《九章算数》, 载 「加」 载「减」 载 「乘」载「除」之术也

**Comment by GalAster** [comment]
有一书名曰 《九章算数》, 载 「求和」之术, 今名之曰 「加」

```py 
from 九章算数 import 求和 as 加
```

**Comment by lanten** [comment]
我注意到书名号的含义非常单一，完全可以将其定义为库或文件的专用符号，可以省略部分关键字，使语法更加简洁。实际场景中更可以在大片的文字中一眼就看出来那些内容是引用自其它文件。

楼上 @GalAster 说的 `载 「求和」之术` 我认为这个 `之术` 是多余的，因为 IDE 在读取文件的时候可以自动做出类型推断，可以省略，不然每次声明都要定义其类型，如 `xxx 之术，xxx之数，xxx之物`，略显繁琐，稍有不慎还会报错。

文件头部的全局解构导入：
```
「霜白」，「黛绿」，「朱红」，载自《万紫千红》
```
对应：
```ts
import { 霜白, 黛绿, 朱红 } from '万紫千红'
```

以相对路径导入：
```
「霜白」，「黛绿」，「朱红」，载自《./定量/万紫千红》
```
这个 `./` 或 `../`  有点违和，但是我实在想不出更好的描述方法。

在函数体中动态导入：
```
吾有一言。载自《./定量/万紫千红》。名之曰「霜白」
```

**Comment by lymslive** [comment]
书名号大善。
但以作者的一个设计思路，除了技术原因不得已保留引号（标识符）外，忽略所有空白与标点符号。
于是我另一个想法，语法技术上将书名号`《》`等同与单引号`「」`，但文法书写（代码编写）规范中推荐以书名号括起模块，以单引号括起标识符。

类似这种设计在 Perl 语言中也有，如在定义 hash 时，逗号`,`与胖箭头号`=>`是等效的：
```perl
my $hash = {'a' => 1, 'b' => 2};
my $hash = {'a', 1, 'b', 2};
```
在 php 中却似乎只能用 `=>` 不能用退化的 `,`表示hash/dict 。

题名话：蓦然发现 perl 的 `my` 与 wenyan-lang 的“吾有”异曲同工啊，perl 的作者也是语言学家，当年力图使用合乎英语语法的方式来书写 perl 脚本。这主旨思想可以借鉴下。

进一步讨论：模块名与模块文件路径（包含后缀.wy）名又是不同的东西。
模块名相当于标识符（命名空间），应该用书名号或单引号括起，导入时自动在搜索路径中按确定规则查找模块文件。
而模块文件名，则是 string ，应该用双引号括起，不管绝对路径还是相对路径，按其字面意思去加载模块代码。

**Comment by antfu** [comment]
Shipped!. Check out https://github.com/wenyan-lang/wenyan/wiki/Importing. Feel free to reopen it if you have any questions :)
