### ISSUE TITLE
error in syntax example in README

### ISSUE THREAD

**Issue by tropurchan** [wenyan-lang/wenyan#121]
The part 
> 昔之「甲」者。今「大衍」是也。

compiles to `a = dayan; };` instead of `a = dayan;`
I believe it should  be 今「大衍」是矣 (?

**Comment by LingDong-** [comment]
Yup you're totally right, it's now fixed: 1a5e12448b6788bdb2ad6e87671114429853f45c
Thanks a lot for spotting the typo!

**Comment by kaiyuan01** [comment]
How about:
昔日之「甲」兮，今直为此「大衍」也。

Syntax: See Chu Ci:
何昔日之芳草兮，今直为此萧艾也？
