### ISSUE TITLE
error met when using render.js

### ISSUE THREAD

**Issue by liuyunhui123** [wenyan-lang/wenyan#136]
I made one helloworld using this language, passed the wy-js and made it running, but I was stuck when trying to render one out.

1. At the beginning, my reports are: 

> "tokens.push(["num",hanzi2num(tok),i]) TypeError: hanzi2num is not a function"

so I went to the issues and found the guy with ['export'](https://github.com/LingDong-/wenyan-lang/issues/115) , but it came out with anothor failure.

2. Then, my reports are: 

> "Cannot read property 'wy2tokens' of undefined"

 at render.js while trying to get the required **parser**.

3. After all those struggles, I finally went across by adding two lines to **hanzi2num.js** as followed:
```
try{
    module.exports = {hanzi2num, num2hanzi};
}catch(e){}
```
and I go my pics.
<img width="298" alt="me" src="https://user-images.githubusercontent.com/20085953/71090515-25de3f80-21de-11ea-81de-172c3482a537.png">

thanks for your language!

-----------
my first time writting an issue, maybe somehow confusing... sorry for that.

**Comment by Landau1994** [comment]
Thanks, that's work for me

**Comment by LingDong-** [comment]
Thanks so much for the detailed report! You found the exact right solution.

The `exports` lines are accidentally removed in a pull request to add tests to `hanzi2num.js`:

https://github.com/LingDong-/wenyan-lang/pull/61/commits/5fe4fcd894f14e3b5bf60ec79422ffc348771f44

I just added that fix and pushed the code. Now it should be working fine
535b0148eb52588756fc1aa542b2058f36ef02ae

Thanks.
