### ISSUE TITLE
没有位运算与逻辑运算

### ISSUE THREAD

**Issue by angle600** [wenyan-lang/wenyan#143]
缺少位运算、逻辑运算

**Comment by LingDong-** [comment]
You're right, please see issues https://github.com/LingDong-/wenyan-lang/issues/2 and https://github.com/LingDong-/wenyan-lang/issues/55 on my plans to implement them

**Comment by antfu** [comment]
Implemented in https://github.com/wenyan-lang/wenyan/blob/master/lib/js/%E4%BD%8D%E7%B6%93.wy
