### ISSUE TITLE
giant/tiny numbers in unit test might fail

### ISSUE THREAD

**Issue by simon300000** [wenyan-lang/wenyan#152]
Currently using macOS 10.15.2 (19C57), Node.js 13.4.0

Basically the big numbers in unit test is hardcoded; but the numbers, the big ones...are little bit "strange" in JavaScript

```diff
2) hanzi2num
hanzi2num("無量大數")
should translate hanzi to number correctly:

AssertionError [ERR_ASSERTION]: 1e+68 == 1.0000000000000002e+68
+ expected - actual

-1e+68
+1.0000000000000002e+68
```
      
ref: #61 #38 #55

<img width="731" alt="image" src="https://user-images.githubusercontent.com/12656264/71126374-d4f13a00-2223-11ea-8b15-692d4843c8f9.png">

**Comment by antfu** [comment]
It should be fixed in recent testing updates. Thanks :)
