### ISSUE TITLE
吾有一计，可助公之访问控制

### ISSUE THREAD

**Issue by OliverS18** [wenyan-lang/wenyan#195]
今公蕴大才抱大器，若以「吾有」名之private，「今有」名之public，岂不美哉！【王司徒脸】

**Comment by fengsi** [comment]
一派胡言！普天之下，莫非王土！【Python从不知private脸】

**Comment by ZeroAurora** [comment]
#290

**Comment by ZeroAurora** [comment]
好像作者有说过这个会实现的，具体哪一个issue/pr忘了

**Comment by ZeroAurora** [comment]
#290
> New usage of 今有. 今有 is now used for exported/public variables, while 吾有 is private/scoped. Think of 今有 like module.exports.x=. Think of 吾有 like var x=
