### ISSUE TITLE
繁体中文，可以考虑简体中文

### ISSUE THREAD

**Issue by DonkeXu** [wenyan-lang/wenyan#209]
简体中文感觉更好一些 ：）

**Comment by ultrakjie** [comment]
古人用的是繁体，用繁体装逼看上去装的更透彻

**Comment by tai1036** [comment]
可以用通用中括号会更好一些，大陆简体中没有这样的写法，十分期待可以用文言写代码，好玩疯了

**Comment by hanyuone** [comment]
懒得一直改键盘啊，但是。。。
能否简繁体都支持，如"等于“和”等於“

**Comment by Yukibana** [comment]
我也觉得用繁体更爽一点啦，写文言不用繁体就没内味儿了（滑稽

**Comment by antfu** [comment]
While Simplified Chinese would not get official support in the near future. You can check out the Simplify package `简体秘术` https://github.com/lymslive/wyg-packages/tree/jiantihua by @lymslive. If you prefer to use Simplified Chinese for wenyan,
