### ISSUE TITLE
吾有一策, 与诸位共商

### ISSUE THREAD

**Issue by GalAster** [wenyan-lang/wenyan#230]
我想要有更多的句式变化, 我试着列了一些我觉得符合语感的说法:

https://wenyan.netlify.com/basic/type.html#%E7%88%BB

现在征求更多的建议, 不管可不可以实现, 都欢迎提议

## 原爻

吾有一爻。曰陽。名之曰「男」。

吾有一爻。曰陰。名之曰「女 」。

## 爻

今有一恒爻。性阴。

此所谓「假」。

另有一恒爻。性阳。

谓之曰「真」。

```ts
const 假: bool = false;
const 真: bool = true;
```

**Comment by melop** [comment]
有爻「男」值陽。
bool Nan = true;

不是更簡單嗎^_^。我覺得文言須簡練，否則無優勢。

**Comment by GalAster** [comment]
一些新想法:

- 假 [value] 为 [var]

- 以 [value] 委之 [var]

- [var] 者, [value] 者也

**Comment by Cyvadra** [comment]
@LingDong- 可否帮忙开贴，收集一下各类建议？
