### ISSUE TITLE
[installation failed]

### ISSUE THREAD

**Issue by chaomenghsuan** [wenyan-lang/wenyan#233]
Installation was failed when running `npm run make_cmdline`
here's part of the log:
```
18 verbose node v13.5.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 2
22 error wenyan-lang@ make_cmdline: `node ./tools/make_cmdline.js && pkg ./build/wenyan.js --out-path ./build`
22 error Exit status 2
23 error Failed at the wenyan-lang@ make_cmdline script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
I wondered what the problem is

**Comment by LingDong-** [comment]
Hi there, thanks for the report. I haven't run into this issue. Maybe it's something wrong with [the pkg packager](https://www.npmjs.com/package/pkg)? Meanwhile you can still run the cmdline tool by using `node ./build/wenyan.js`
Thanks.

**Comment by antfu** [comment]
We are now using npm to ship the js executable. You can check https://github.com/wenyan-lang/wenyan#command-line-compiler for more details. Hope it solves your issue. Closing for now.
