### ISSUE TITLE
Online IDE typing error

### ISSUE THREAD

**Issue by zcoco99** [wenyan-lang/wenyan#250]
Online IDE使用拼音输入法的时候，选完字，按下空格或回车，就会把整个页面的代码复制一次，而且选择的汉字也没打出来。

**Comment by LingDong-** [comment]
Thanks for the report. This problem seems to be originated from a pull request I merged earlier today that allows automatic syntax highlighting. It seems also dependent on the browser and system input method. I'll look into this

**Comment by LingDong-** [comment]
I added a checkbox to "opt-in" to auto highlight. This way it will never conflict with input method by default. And if you're feeling lucky, you can turn it on.

Thanks.
