### ISSUE TITLE
SublimeText plugin for Wenyan.

### ISSUE THREAD

**Issue by absop** [wenyan-lang/wenyan#276]
I created a sublime text's plugin  for Wenyan, [here](https://github.com/absop/SublimeWenyan) it is.
I wonder if it can be added to the Contributed Tools.

**Comment by LingDong-** [comment]
Nice! No problem, I added it to Contributed Tools. Thanks for the plugin!

**Comment by absop** [comment]
Thanks, and it's my honor.
