### ISSUE TITLE
Is there any possibility to parse original Classical Chinese?

### ISSUE THREAD

**Issue by xubaiw** [wenyan-lang/wenyan#279]
我注意到《九章算经》有这样一句话：
Noticing that the Nine Chapters has it that:

```OriginalClassicalChinese
術曰、母相乘為法、子相乘為實、實如法而一。
```

我觉得如果真的可以编译这种写法的话让wenyan-lang更加简洁，并且更加实用（我也知道它会有语义模糊的问题……
I think this style (if it can be parsed) will make wenyan-lang more elegant and more practical, despite the problem of ambiguous meaning.

我发现在这样的句子里像“相”、“为”、“如”、“而”这样的虚词占了很大一部分，从虚词作为停止词进行分词（加上一些特殊的编译方法？），而不是传统的tokenizer-parser，是否可以解决这个问题？
In such sentences in which function words play an important role, can we solve the problem with a special parsing method(, which use function words as their stop words) instead of the traditional tokenizer-parser method?

顺带一提，README提到wenyan-lang采用了基于NLP的文言语法，是否可以详细解释一下编译器采用的NLP呢？(*≧ω≦)
By the way, README mentioned that wenyan-lang uses a syntax based on NLP, can anyone tell me where is the NLP part? (*≧ω≦)

如果这个语言真的采用NLP的话，其实语义模糊应该不是问题，况且文言文本身语法就会比较严谨（虚词大量使用且功能分化明确？）应该比现代汉语更容易解决？我觉得wenyan-lang的初衷或许应该是让文言 programmable ，而不是 adapting 文言 to programming language（？理解错了勿怪）。我会研究一下如何用NLP解决不加「」导致的歧义问题。
My English is poor. I cannot translate my words...

**Comment by frederick-vs-ja** [comment]
我个人的态度不乐观。
目前有一种观点，认为上古时期汉语是有变格的，表现在声母的清浊交替和韵尾交替（后来导致声调差异），但这些变格没有体现在书写的汉字上。这导致书写出来的文言文无法如想象的那般严谨，从而编程语言也不适合直接使用原本的文言文。

**Comment by AshyAzure** [comment]
是的，会存在这种问题。所以我认为是个很有意思的研究方向（？）
这种变格显然也是和上下文相关的，因此我觉得可以用NLP或者相关的方法解决？
（在读《马氏文通》😏

**Comment by LingDong-** [comment]
@AshyAzure 
Jus to clarify, NLP in the readme refers to [Natural Language Programming](https://en.wikipedia.org/wiki/Natural-language_programming). Not Natural language processing or even Neuro-linguistic programming as one might think
Sorry for the confusion. I'll change the README.
But I'm also happy to explore "real" NLP for the project ;)
