### ISSUE TITLE
吾有一策, 可解修饰词

### ISSUE THREAD

**Issue by GalAster** [wenyan-lang/wenyan#289]
public/private 的话可以我觉得可以这样, 只要包含第一人称物主代词, 比如 吾/私, 那就是 private, 不然都是 public:

- public:

```
今有一数五十名之曰 [甲]
兹有一数五十名之曰  [乙] 
现有数曰五十名之曰  [丙]
有数五十名之曰 [丁]
```

- private:

```
吾有一数曰五十名之曰  [戊]
私数五十名之曰  [己]
```

这样也好扩展, 比如有 恒/常 这样的词的话就是 final/const

- final private:

```
吾有一恒数曰五十名之曰  [庚]
```

更更多的前缀修饰词可以这样:

```
有物名[object], 此物 [mod1][mod2][mod3], 名之曰 [name]
```

_Originally posted by @GalAster in https://github.com/LingDong-/wenyan-lang/issues/278#issuecomment-568131684_

**Comment by LingDong-** [comment]
Hi, thanks for the proposal!

See #290, `今有` and `吾有` are already used to distinguish public & private :)
恒 and the multiple prefix syntax looks interesting too! I'll consider them when I add more OOP related features.
