### ISSUE TITLE
用"文言"的古音类似“myungyon”,"moonyeon"

### ISSUE THREAD

**Issue by guxd** [wenyan-lang/wenyan#295]
大家的建议都在书面语上，我从读音上提个建议。"wenyan"是现代汉语读音，可不可以用古汉语读音类似"myungyon", "moonyeon"作为语言的名称。
(While everyone's suggestions are in written language,  I would make a suggestion from pronunciation: since "wenyan" is the pronunciation in modern Chinese, can you use ancient Chinese pronunciation like "myungyon" and "moonyeon" as the language name. )

**Comment by LingDong-** [comment]
I think your suggestion is very good, however:

- I wish I thought about this earlier. Now that everything in the repo is named wenyan, it is quite a pain to switch. Plus many people already know this project as wenyan-lang. I just think it's too late to change :(
- moonyeon has a possibility to be read as moony-eon (dreamy years?). Kind of romantic haha.

But I'll definitely take these kind of things into consideration for the next project.
Thank you very much!

**Comment by Elysion-tcfa** [comment]
值得一提的是，“moonyeon”只是韩语读音，韩语读音不等于中古音，中古汉语中“言”是疑母字，声母应为/ng/，而不是韩语里面的零声母。

**Comment by guxd** [comment]
@Elysion-tcfa 谢谢指正。

**Comment by heangfat** [comment]
文：微紐、三等、合口、文韻(平聲)。
言：疑紐、三等、開口、元韻(平聲)。
所謂 moon yeon 二字讀音俱誤。建議關閉問題。

**Comment by guxd** [comment]
@heangfat 我只是举个例子建议用古音，又没有说一定要用我举的这个发音。你是专家可以提你的建议。不要动不动建议删别人的问题。而且我也听取建议认为中古汉族拟音更好。

**Comment by heangfat** [comment]
@guxd 抱歉，失言了。我意爲不贊成現階段用古音轉寫。

**Comment by guxd** [comment]
@heangfat 嗯，我也覺得慢慢過渡比較好。雖然古文+古音是最完美的，但是這可能會把不少沒接觸古漢語讀音的人拒之門外，曲高和寡，哈哈
