### ISSUE TITLE
More flexible use of auxiliary words

### ISSUE THREAD

**Issue by xubaiw** [wenyan-lang/wenyan#306]
Should auxiliary words such as “也” “云云” “矣” and “之” be used strictly?
In the source code there are

<img width="487" alt="截屏2019-12-21下午4 07 23" src="https://user-images.githubusercontent.com/20809612/71305255-fdd42380-240b-11ea-95b4-6255223d83b5.png">

and

<img width="257" alt="截屏2019-12-21下午4 05 21" src="https://user-images.githubusercontent.com/20809612/71305241-b51c6a80-240b-11ea-9404-964b844754ed.png">、

The word “也” “云云” are simply mapped to `};`

Therefore we can't use words in such syntax:

`昔之「甲」者。今之「大衍」是矣。`  Wrong❌
`昔之「甲」者。今「大衍」是矣。`  Right✔️

`若三不大於五者。乃得「「想當然耳」」。若非。乃得「「怪哉」」是矣。` Wrong❌
`若三不大於五者。乃得「「想當然耳」」。若非。乃得「「怪哉」」也。` Right✔️

`吾有一物。名之曰「甲」。其物如是。物之「「乙」」者。數曰三。物之「「丙」」者。言曰「「丁」」。是謂「甲」之物矣。` Wrong❌
`吾有一物。名之曰「甲」。其物如是。物之「「乙」」者。數曰三。物之「「丙」」者。言曰「「丁」」。是謂「甲」之物也。` Right✔️

And it's also inconvenient to expand our keywords to compound auxiliary words like “已矣”
Can we use some universal "end" token to solve it?

**Comment by GalAster** [comment]
应该是可以的

很多比较老或者保守的语言就是

- if...endif
- for...endfor
- while...endwhile
- function[name]...endfunction[name]

现在一些新的语言就用

- if...end
- for...end
- while...end
- function[name]...end

**Comment by AshyAzure** [comment]
Yes, I think in natural language programming the code should be written without pondering on which word is correct.(⊙v⊙)
