### ISSUE TITLE
IDE也取个古文名呗

### ISSUE THREAD

**Issue by Chee94** [wenyan-lang/wenyan#311]

**Comment by GalAster** [comment]
不如叫 子曰

**Comment by jingyuexing** [comment]
文渊阁？

**Comment by jingyuexing** [comment]
尽是文言文，一个IDE是类似一个写书的的地方
古代刻本分为三类官刻本、家刻本、坊刻本，官方刻本一般有监本比如我们熟悉的国子监，经场本，殿本(`武英殿`)，内府本，局本
这算是文言文的官方版，算是`官刻本`吧，正好IDE可以渲染出古籍的版式，也许可以叫做`文渊堂`？ 
:smiley:

**Comment by kaiyuan01** [comment]
武英殿，我很喜欢

**Comment by liangei** [comment]
天工開物

**Comment by yanzhao77** [comment]
宜春院

**Comment by yanzhao77** [comment]
怡红院

**Comment by antfu** [comment]
Oh, we have it now called `文言齋` https://github.com/wenyan-lang/ide

And for the `文渊阁` we used it as the package manager for wenyan https://github.com/wenyan-lang/wyg

Thanks for all the suggestions!
