### ISSUE TITLE
Is there a way to save `a == b` to a boolean variable?

### ISSUE THREAD

**Issue by zxch3n** [wenyan-lang/wenyan#317]
Current behavior

```
吾有一爻。曰五等於三。
```

=> 

```
var _ans1 = 5;
```

Expected

```
var _ans1 = 5 == 3
```

I'm working on a parser to parse js to Wenyan. To parse an AST to a Wenyan ASC, I need to calculate and store some variables outside of the if's test statement. But restricted by current grammars, it seems not possible.

**Comment by LingDong-** [comment]
Hi, this is the current way to do it:

```
吾有一爻。若五等於三者。昔之其者。今陽是矣云云。
```

I know it is slightly inconvenient, I'll think about ways to do it more directly. Perhaps there will be a standard library function called `「比」`

```
施「比」於三於五。名之曰「甲」
```

Thanks for bringing this up, and good luck on your reverse parser!

**Comment by zxch3n** [comment]
Thanks!
