### ISSUE TITLE
Enabling Function Input Parameters of Different Types

### ISSUE THREAD

**Issue by Youcheny** [wenyan-lang/wenyan#318]
Hi Lingdong,

Right now Wenyan cannot support functions with input parameters of different types, or so it seems on the README. 
![image](https://user-images.githubusercontent.com/25046973/71310546-6d6c0200-2450-11ea-9936-976f8c053b88.png)
Would it be nice if we could have functions with different input types? I was trying to write a binary search function that takes an array and an int as input and this frustrates me a little. 

If this feature is there, it would be great if we can have it on the README. If not, please see if my humble suggestion is worth any value and if it will be possible to implement:
`吾有一術。名之曰「二分查找」。欲行是術。必先得一列。曰「列」。一數。曰「數」。`
If you need me to collaborate on / look into this, I'd be happy to once I have time.

**Comment by LingDong-** [comment]
Hi there, 

Your suggestion is already supported. Even the syntax is exactly the same! See:

https://github.com/LingDong-/wenyan-lang/issues/289#issuecomment-568137483

It should be working correctly, check out the `./examples/turing` example for more usage.

I should probably put it in the README :). Thanks for bringing this up.

**Comment by t-a-n-0** [comment]
Actually,as wenyan code is parse to Dynamically Typed Language code like JavaScript,when you call the method,you can send values that don't match the type you declare them,but it doesn't look good.

**Comment by LingDong-** [comment]
@t-a-n-0 . No need to do that! there is already the syntax for having arguments of different types:

```
吾有一術。名之曰「二分查找」。欲行是術。必先得一列。曰「列」。一數。曰「數」。
```

In the turing machine example:

```
吾有一術。名之曰「圖靈機」。欲行是術。必先得一列。曰「諸律」。二言。曰「始態」。曰「終態」。
```

Moreover, I'll soon make the compiler stricter so it becomes harder to do goofy things like this.
Thanks.

**Comment by t-a-n-0** [comment]
> @t-a-n-0 . No need to do that! there is already the syntax for having arguments of different types:
> 
> ```
> 吾有一術。名之曰「二分查找」。欲行是術。必先得一列。曰「列」。一數。曰「數」。
> ```
> 
> In the turing machine example:
> 
> ```
> 吾有一術。名之曰「圖靈機」。欲行是術。必先得一列。曰「諸律」。二言。曰「始態」。曰「終態」。
> ```
> 
> Moreover, I'll soon make the compiler stricter so it becomes harder to do goofy things like this.
> Thanks.

Wow.Maybe it will have some parsers to parse wenyan code to Statically Typed Language code and will have better performance in the future.

**Comment by LingDong-** [comment]
@t-a-n-0 That's exactly the goal :)

**Comment by antfu** [comment]
Refer to #486
