### ISSUE TITLE
[Feature Proposal] Renderer Export Feature for Online IDE

### ISSUE THREAD

**Issue by Youcheny** [wenyan-lang/wenyan#324]
Hi Lingdong,

I am thinking if we can have an export button on the online IDE that allows the user to download the renderer-generated version of the code with the click of a button as an alternative to using render.js. I know that there are ways to do this without the use of a server and it is both easy to implement and very appealing for users who want a "souvenir" of the code they wrote (like myself). Again, if you would like my help with this, I'd be happy to do it as I've been looking at that piece of code for a while trying to figure out render.js.

**Comment by LingDong-** [comment]
Hi @Youcheny, I think that's a great idea! Shouldn't be hard to implement, in fact I can add it next time I work on the online IDE. But if I need help I'll let you know, thank you very much!

**Comment by antfu** [comment]
FYI, If you are using VSCode, the [vscode extension](https://github.com/antfu/wenyan-lang-vscode) can do that for you already.

**Comment by antfu** [comment]
It's implemented on the new overhauled Online IDE. Please do check it out https://wy-lang.org/ide
