### ISSUE TITLE
webpack plugin support

### ISSUE THREAD

**Issue by njzjz** [wenyan-lang/wenyan#325]
It will be better if there is a webpack plugin (maybe named wenyan-loader or wy-loader), which can be just like ts-loader (https://webpack.js.org/guides/typescript/). And then, we can compile wy easily with webpack.

**Comment by antfu** [comment]
Hi @njzjz 
I have just made a wenyan-loader for webpack, feedbacks are welcome!
https://github.com/antfu/wenyan-loader
Rollup plugin is also available FYI.
https://github.com/antfu/wenyan-rollup-plugin

cc @LingDong- if you are good with it, I can transfer them to the org :)

**Comment by LingDong-** [comment]
👍

> if you are good with it, I can transfer them to the org :)

Sure! As for code names...

rollup (sleeves) 文言攘臂
rollup (luggage) 文言鋪蓋
rollup (paper) 文言卷軸
...

**Comment by antfu** [comment]
> rollup (luggage) 文言鋪蓋

To me, maybe rolling up luggage matches better with what rollup is doing 🤣
