### ISSUE TITLE
吾有一疑于书, 望诸位共商之

### ISSUE THREAD

**Issue by GalAster** [wenyan-lang/wenyan#336]
征集一下以下语法

## 导入

吾尝观「「算經」」之书。方悟「正弦」「餘弦」「圓周率」之义。

```py
from 算經 import 正弦, 餘弦, 圓周率
```

## 函数别名

吾尝观「「Math」」之书。方悟「sin」之义。夫「sin」。名之曰「正弦」。

```py
from Math import sin as 正弦
```

## 包别名

吾尝观「「Math」」之书。夫「Math」。名之曰「算經」。

```py
import Math as 算經
```

## 全导入

??

```py
from 算經 import *
```

## 重导出

??

```ts
export * from 算經
```

## 相对路径

??

```py
import .算經
```

```py
import 算經.算術篇
```

**Comment by LingDong-** [comment]
Thanks for bringing this up.

Here are statements that are already supported out of the box:

```
from Math import sin as 正弦

吾尝观「「Math」」之书。方悟「sin」之义。夫「sin」。名之曰「正弦」。
```

```
import Math as 算經

吾尝观「「Math」」之书。夫「Math」。名之曰「算經」。
```

Feel free to suggest syntax sugars these and other ones. The philosophical question is how much sugar do we want ;)

**Comment by sparkmxy** [comment]
全导入
「算經」之术备矣。
`from 算經 import *`

**Comment by Lotayou** [comment]
@sparkmxy I think a full import could be dangerous, as different packages could contain methods with same names, such as `random.randn`, `numpy.randn`, `torch.randn`. If a project happens to import two packages together, it could lead to ambiguity when calling some common functions.
