### ISSUE TITLE
说白了！就是用文言文做js的变量名？？

### ISSUE THREAD

**Issue by Notobey** [wenyan-lang/wenyan#339]
看了一些例子，好像这个项目的最后使用js来实现的，好像就是做了一个转换吧？？

**Comment by AlexanderMisel** [comment]
当然不是这样。这是一个全新的编程语言，因为它会按照自己定义的文法进行编译，而不是把JS的变量转换一下。底层实现是什么语言不影响什么。

**Comment by Notobey** [comment]
> 当然不是这样。这是一个全新的编程语言，因为它会按照自己定义的文法进行编译，而不是把JS的变量转换一下。

受教

**Comment by antfu** [comment]
Closing for now. If you get any questions, feel free to reopen it.
