### ISSUE TITLE
Need instructions for contributors

### ISSUE THREAD

**Issue by kaiyuan01** [wenyan-lang/wenyan#346]
For those who really wanted to help but not heavy npm package developers, please add a page for contributors - how can they build and test this locally? The main page is only for end users.

We may also add more test cases to cover the code - this can only be done by contributors/developers as well, not the end users of this package. Please help.

**Comment by LingDong-** [comment]
Hi @kaiyuan01 , 

@antfu might be better at answering this question, he built all the nice npm stuff for this repo. For lightweight npm user like myself, one can simply run the script `tools/make_ide.js` and go to `site/ide.html` to check the changes. Sometimes I run the commandline tool `tools/cli.js` directly. There is also a page explaining the testing method we're using: `documentation/Testing.md`

Please feel free to add more test cases and submit a PR, that would be very much appreciated! 

Thank you!

**Comment by antfu** [comment]
@kaiyuan01 Thanks for the suggestion! I will try to add the docs to this very soon. Please keep tuned.

**Comment by kaiyuan01** [comment]
@LingDong- @antfu Thank you. Will give it a try and update

**Comment by antfu** [comment]
You can refer to this now: https://github.com/wenyan-lang/wenyan/wiki/Contributing
