### ISSUE TITLE
尤大大带一下就是不一样，几天就火成这个样子！

### ISSUE THREAD

**Issue by theajack** [wenyan-lang/wenyan#354]
这个[中文项目](https://github.com/theajack/cnchar)也很不哦错哦！😘

**Comment by AlexanderMisel** [comment]
说实话我之前还真不知尤雨溪赞过，我是看qq群别人发图知道的。

**Comment by theajack** [comment]
@AlexanderMisel 
我 follow 了尤雨溪，他star当时我就收到消息了，但是这个项目还只是2k的star好像

**Comment by antfu** [comment]
Closing for now. If you get any questions, feel free to reopen it.
