### ISSUE TITLE
Label issues

### ISSUE THREAD

**Issue by liyishuai** [wenyan-lang/wenyan#364]
I came up with a technical issue and wanted to browse whether it was raised before, so as to avoid duplicance. However, the issue tracker is filled with "comments", "humor", and "到此一游" topics.

May I recommend the maintainer to kindly classify issues by "technical", "miscellaneous" etc. for the convenience of contributors?

---
**Disclaimer**: I understand that GitHub is used very differently in Chinese community. We should not blame some "not so GitHub" usages, if GitHub is the only place to do so.

Nevertheless, I still believe that many discussions in this repo fit way better elsewhere. This might be common for "popular overnight among beginners" projects. Hopefully there'll be some solution.

**Comment by antfu** [comment]
Totally agreed. Code of conduct and issue templates may also help people better contribute to this project. I would love to do this if @LingDong- feels good about it 😄

**Comment by LingDong-** [comment]
@liyishuai  Okay! I just spent some time to give every issue a tag :)
@antfu, sounds like a great idea! Thanks for your help!
