### ISSUE TITLE
吾亦有一策，與諸君同議！

### ISSUE THREAD

**Issue by sandyzikun** [wenyan-lang/wenyan#374]
建議出一套適配於`highlight.js`之語法高亮標準。

另，`fork`已企及`666`：
![文言](https://user-images.githubusercontent.com/36362203/71405625-f82b4780-2670-11ea-9567-f51429dadb6d.jpeg)

**Comment by antfu** [comment]
We have a collection of syntax highlighters now, please do check it out: https://github.com/wenyan-lang/highlight
