### ISSUE TITLE
使用變數作為鍵值

### ISSUE THREAD

**Issue by hiking93** [wenyan-lang/wenyan#388]
舉例來說

```
吾有一物。名之曰「甲」。
昔之「甲」之「「測試」」者。今百是矣。
吾有一言。曰「甲」。書之。
```
輸出：
```
{ '測試': 100 }
```

但是
```
吾有一言。曰「「測試」」。名之曰「鍵」。
吾有一物。名之曰「甲」。
昔之「甲」之「鍵」者。今百是矣。
吾有一言。曰「甲」。書之。
```
輸出：
```
{ NaN: 100 }
```

其中
```
昔之「甲」之「鍵」者。今百是矣。
```
編譯成了
```
甲[鍵 - 1] = 100
```

**Comment by zxch3n** [comment]
I just wanted to raise an issue about this. What a coincidence.

It seems we need a new grammar or use a type checking function before indexing.

**Comment by LingDong-** [comment]
Hi @hiking93 @zxch3n ,

You are both correct, I too have been thinking about how to fix this issue for a while now, here are some ideas I have:

### Method 1: Runtime typecheck

Compile to:

```
甲[((typeof 鍵 == 'number')?(鍵-1):鍵)] = 100
```
Downside: ugly and makes code slightly slower

### Method 2: Static type inference

In the compiler, remember/infer what type each variable is when it is declared. But there are a lot of cases that needs to be handled and requires some true work. But this should eventually be one of the ultimate goals of this language.

### Method 3: Syntax change

Add another keyword for indexing using string variables. This feels like a hack so unless we can think of a really good name for the keyword I don't think we should do it.

### Method 4: stdlib

Have a stdlib which has a collection of object-related functionalities, and one of them is a function that takes two arguments, an object and a string, and returns object[string]. I think it is very likely that there'll be a stdlib that concerns objects, similar to JS `Object.xx` functionalities. So it sounds reasonable to have such a function there.

Downside: people might not know of the function and get surprised when `「甲」之「鍵」` doesn't work as they might expect.

### Method 5: Won't fix

If you think of `物` as struct/class in C/C++, many languages doesn't provide easy way to access fields of datastructures by a string containing the key. It simply has to be obj.key or obj->key etc. But of course, this is the least nice solution of the 5 :P

Please let me know what you all think! Thank you!

**Comment by hiking93** [comment]
> If you think of `物` as struct/class in C/C++, many languages doesn't provide easy way to access fields of datastructures by a string containing the key. It simply has to be obj.key or obj->key etc. But of course, this is the least nice solution of the 5 :P

Actually I found this issue while using that `物` as a map to store data.

**Comment by hiking93** [comment]
@LingDong- BTW, what's the reason for making arrays 1-indexed?

**Comment by zxch3n** [comment]
@hiking93 1-indexed behavior makes more sense in the context of the ancient Chinese language. I guess a significant part of the initial intention of building this project is to make the language coherent in ancient Chinese language.

**Comment by cuixiping** [comment]
I like Method 3: Syntax change. so we can distinguish between variables and literals.

**Comment by zxch3n** [comment]
I prefer to make a syntax change too. The overhead of it is the lowest.

### As for Type inference

The static type inference may not be very useful, because the type of a variable could be `string|number` from a function like this:

```javascript
function v(){
	if (Math.random() < 0.5) return 1;
	return '1';
}
```

There is no way to figure out the actual type unless making the whole language static or checking type at runtime.

**Comment by lymslive** [comment]
I like method 4 and method 5, since I'm C++ coder now.
