### ISSUE TITLE
为什么一定要繁体字呢？

### ISSUE THREAD

**Issue by ixiadao** [wenyan-lang/wenyan#389]
用简体字的人应该比繁体字的人多的多吧？虽然可以切换繁体字，但是是不是显得太过麻烦？编程的目的应该是为了提高效率吧？化简为繁可能不太好？

**Comment by hiking93** [comment]
真要高效率的話不會選這個語言吧。

照這個邏輯看來，熟悉白話文的人也比文言文多的多，應該全面改成白話。

**Comment by ixiadao** [comment]
> 
> 
> 真要高效率的話不會選這個語言吧。
> 
> 照這個邏輯看來，熟悉白話文的人比文言文多的多，應該全面改成白話。

我并未否认其文言文语法构造，我只是在谈输入方便性而已。

**Comment by hiking93** [comment]
> 我并未否认其文言文语法构造，我只是在谈输入方便性而已。

嗯，我想如果能繁簡通用的話也挺不錯的。

**Comment by cuixiping** [comment]
用繁体比较有范，用简体方便，不过现在输入法很容易切换，输入不是问题。
当然，如果简繁通用，确实更方便（方便写的人是一方面，另一方面是方便阅读者）

**Comment by kaiyuan01** [comment]
Let's start from tranditional Chinese as the point is wenyan-lang. If you are onto making this more useful, consider contributing to the project to make a tool to convert b/w two styles of Chinese characters.

What's more, everyone agrees that if you like Chinese culture and the classic literature, it's a must to learn some basic traditional Chinese anyway, IMHO

**Comment by fanwanyong** [comment]
文言文读起来，虽然听不懂！但是好像很屌的样子！要是用我有一函数！那不是很土鳖(：

**Comment by cuixiping** [comment]
> 文言文读起来，虽然听不懂！但是好像很屌的样子！要是用我有一函数！那不是很土鳖(：

:joy_cat: :joy_cat: :joy_cat: 
你可以不用普通话啊，选择很多的，比如东北话：俺这旮旯整了个函数，再比如：伦家有函数嘛~

**Comment by Albertchamberlain** [comment]
@cuixiping 思路不错，说不定以后真有人在作者的基础上，衍生出了方言版的，C00l...

**Comment by lymslive** [comment]
我觉得语法关键字用繁体没问题，风格明显。
但简体是使用者的选择，比如用于标识符，这也使得两者更易于区分。
至于输入的便利性，是外部辅助工具的话题，比如 IDE 或编辑器插件在保存时自动转为
繁体关键字。

**Comment by wks** [comment]
wenyan語言就是所謂的esoteric programming language。目的就是驗證某種古怪的思想能不能行得通。這個語言的目的就是模仿古代算數書的文法來編程，就是這個語言的樂趣所在。如果真的關注易用性，可以考慮python，一定要中文的話，「中蟒」的可讀性也很好。

**Comment by liangzhonghao** [comment]
> > 文言文读起来，虽然听不懂！但是好像很屌的样子！要是用我有一函数！那不是很土鳖(：
> 
> 😹 😹 😹
> 你可以不用普通话啊，选择很多的，比如东北话：俺这旮旯整了个函数，再比如：伦家有函数嘛~

俺们东北人不用俺

**Comment by antfu** [comment]
While Simplified Chinese would not get official support in the near future. You can check out the Simplify package `简体秘术` https://github.com/lymslive/wyg-packages/tree/jiantihua by @lymslive. If you prefer to use Simplified Chinese for wenyan,
