### ISSUE TITLE
`continue` keyword

### ISSUE THREAD

**Issue by zxch3n** [wenyan-lang/wenyan#392]
## Describe your issue/suggestions

Add a `continue` keyword

**Comment by Lotayou** [comment]
这不是有现成的词嘛——“续”……稍等，我去拿个快递

**Comment by LingDong-** [comment]
Thanks for bringing this up!

I think the concept of `continue` is somewhat hard to describe. Even the english word `continue` doesn't describe what this statement does very accurately. `skip_the_rest_of_this_iteration_and_start_the_next_iteration_now` would be a lame but more accurate name. How best can we explain this to 古人? `(弃/废/去)此回`?`请听下回分解`?

Would love to hear everyone's opinion.

**Comment by cuixiping** [comment]
Or
```
為是百遍。
    若三大於二者。此遍乃止。
云云。
```

**Comment by S-Asakoto** [comment]
How about using "乃避" (to avoid)? In this sense to avoid the remaining code inside the loop.

**Comment by lymslive** [comment]
A line come up in my brain: "稍待片刻，俺老孙去去便回" ^_^
How about "即刻轮回"?
"乃避" is acceptable, I think, and also another similar word "乃回".
