### ISSUE TITLE
名之曰「变数」。書之。--不能输出信息

### ISSUE THREAD

**Issue by weifding** [wenyan-lang/wenyan#405]
`施「大衍求一」於四十九。於十四萬二千八百五十七。名之曰「乘率」。書之。`

**想输出下「乘率」，但实际代码是console.log();，无果！**

在fizzbuzz里面有个sample code，

`吾有一言。曰「戊」。書之。`

运行正常。

**Comment by cuixiping** [comment]
去掉 `名之曰「乘率」。` 即可
或者加入 `夫「乘率」`
```
施「大衍求一」於四十九。於十四萬二千八百五十七。書之。
施「大衍求一」於四十九。於十四萬二千八百五十七。名之曰「乘率」。夫「乘率」。書之。
```
