### ISSUE TITLE
吾有一术，若有空可也，或于作者之谏

### ISSUE THREAD

**Issue by MagicLu550** [wenyan-lang/wenyan#411]
余欲为文言撰一反编译器也，或译其犀码为爪哇乎，以通爪哇之虚拟机也，顺应世界之天法，扬天下之公理。中华寻为领天下者，是时也。
若吾有余时，可助之，若君有意，可为之。

**Comment by LingDong-** [comment]
Hi @MagicLu550 ,
More compilers to other languages are always welcome. If you could help it would be very much appreciated! Thanks!

**Comment by MagicLu550** [comment]
> Hi @MagicLu550 ,
> More compilers to other languages are always welcome. If you could help it would be very much appreciated! Thanks!

https://github.com/MagicLu550/wenyan-lang_jvm
I will finish it shortly. I am currently a high school student and I am busy with my studies. I will write it from time to time.Thank you!

**Comment by TangMonk** [comment]
Issue回复以英文，不够文言之气也。:P

**Comment by MagicLu550** [comment]
> Issue回复以英文，不够文言之气也。:P

哈哈😂

**Comment by MagicLu550** [comment]
https://github.com/MagicLu550/wenyan-lang_jvm
有事一求，君若同，亦可撰之于README，以助JVM之用户，今已实现部分之语法

**Comment by LingDong-** [comment]
@MagicLu550 
Awesome! I've added your project to the README
Keep up the good work :) Looking forward to it

**Comment by MagicLu550** [comment]
> @MagicLu550
> Awesome! I've added your project to the README
> Keep up the good work :) Looking forward to it

Thank you very much!I will.

**Comment by MagicLu550** [comment]
Could you please invite me to join the organization? I will contribute my project to this organization.Thank you very much.

**Comment by LingDong-** [comment]
Hi @MagicLu550, please give us some time to consider this. On one hand, we are so glad about your enthusiasm, and we’re very excited about the JVM compiler. It seems to be looking pretty good, congrats! 

On the other hand, the compiler seems to be in a relatively early stage, and as myself only know a little bit Java, and given all the other stuff we need to maintain and develop, we just feel a tiny bit concerned about how well we can support it as an official asset under the organization. You might have noticed the main spec is also constantly evolving. But please don’t let this discouragement! I’ll take a closer look at your code and make further considerations. Meanwhile, really looking forward to its development! Thanks!

**Comment by MagicLu550** [comment]
OK, I will wait patiently, I will maintain this project steadily, and follow up the specifications continuously.Thank you very much

**Comment by MagicLu550** [comment]
Current progress
Not yet implemented. `Macro`,` Exception`, `Object`,` Stack call method`, the syntax mentioned in the rest of the readme and the syntax I have found so far have been implemented.

At the same time, the grammar is customized and can be freely translated into other languages.

And added project management for java-based classical Chinese projects, with a preliminary project structure

Implemented WenYanShell, and enabled command line interaction via `java -jar wenyan.jar shell`

**Comment by LingDong-** [comment]
@MagicLu550 

This looks great, congratulations 🎉!

Please feel free to [transfer](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) Wenyan4j to wenyan-lang organization. I'll accept your transfer request, and you should automatically become the admin of that project. And let's rename it to `wenyan-lang/jvm`, unless you particularly like the current name. If so, please do lowercase `wenyan4j` to conform with styling of `wenyan-lang`.

Thank you so much! Looking forward to it!

**Comment by MagicLu550** [comment]
> Mag
> 
> 看起来不错，恭喜 🎉！
> 
> 请随时[将](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) Wenyan4j [转移](https://help.github.com/en/github/administering-a-repository/transferring-a-repository)到wenyan-lang组织。我会接受您的转移请求，您应该自动成为该项目的管理员。`wenyan-lang/jvm`除非您特别喜欢当前名称，否则将其重命名为。如果是这样，请使用小写形式`wenyan4j`以符合的样式`wenyan-lang`。
> 
> 非常感谢！期待它！

ok,thank you

**Comment by MagicLu550** [comment]
`You don’t have the permission to create public repositories on wenyan-lang`
Oh sorry, I seem to need permission ... Trouble you

**Comment by MagicLu550** [comment]
> @MagicLu550
> 
> This looks great, congratulations 🎉!
> 
> Please feel free to [transfer](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) Wenyan4j to wenyan-lang organization. I'll accept your transfer request, and you should automatically become the admin of that project. And let's rename it to `wenyan-lang/jvm`, unless you particularly like the current name. If so, please do lowercase `wenyan4j` to conform with styling of `wenyan-lang`.
> 
> Thank you so much! Looking forward to it!

Ok,Thank you(刚刚误触了谷歌翻译的按钮)

**Comment by LingDong-** [comment]
@MagicLu550 Oops, sorry I didn't realize Github has this permission issue. I've sent you an invite to become a member ;)

**Comment by MagicLu550** [comment]
> @MagicLu550 Oops, sorry I didn't realize Github has this permission issue. I've sent you an invite to become a member ;) this will allow you to do the transfer.

No problem,Thank you

**Comment by antfu** [comment]
@MagicLu550 Congrats and Welcome! 🎉

**Comment by MagicLu550** [comment]
> @MagicLu550 Congrats and Welcome!

Thank you!😃👏

**Comment by antfu** [comment]
> Wenyan4j's progress will be explained here

Looks great! One little suggestion here is that you can keep this in the `CHANGELOG.md` file of the project root. It can help people better track the changes. Anyway, awesome job!

**Comment by MagicLu550** [comment]
> > Wenyan4j's progress will be explained here
> 
> Looks great! One little suggestion here is that you can keep this in the `CHANGELOG.md` file of the project root. It can help people better track the changes. Anyway, awesome job!

OK,thanks for your suggestions,i will do it.wait me for some time.😁

**Comment by MagicLu550** [comment]
@LingDong- emm...Excuse me,I want to use the settings of the jvm project(wenyan4j before),so i want the owner permission if you agree,thank you.

**Comment by antfu** [comment]
@MagicLu550 Permission granted as Admin of the repo. :)

**Comment by MagicLu550** [comment]
> @MagicLu550 Permission granted as Admin of the repo. :)

thanks ：）

**Comment by MagicLu550** [comment]
By the way,I want to know when the wenyan can support `class`

**Comment by antfu** [comment]
> By the way, I want to know when the wenyan can support class

Please subscribe #31 for updates.

Closing this for now :)

**Comment by MagicLu550** [comment]
> > By the way, I want to know when the wenyan can support class
> 
> Please subscribe #31 for updates.
> 
> Closing this for now :)

ok,thanks,now I am busy with my studies recently, so the project is temporarily stagnant.Hope for understanding:)
