### ISSUE TITLE
项目怎么跑起来

### ISSUE THREAD

**Issue by puchenhui** [wenyan-lang/wenyan#418]
我把代码拉下来之后不知道该怎么运行起来

**Comment by antfu** [comment]
Please checkout the readme for installation section. You can use the online ide, text editor extensions or install using npm. Thanks

**Comment by puchenhui** [comment]
我用npm安装了，找不到应该怎么把这个运行到浏览器

**Comment by TangMonk** [comment]
@antfu project is about  ancient Chinese, reply is English, seems weird. I think you can：

```
有一书简，名曰 ReadMe，汝可观之。或假以online ide试之。
```

**Comment by puchenhui** [comment]
吾乃略读ReadMe,但仍未解鄙人之惑。不知兄台用其方法可否实现？

**Comment by antfu** [comment]
If you want to run the compiler by yourself, you can read this document https://github.com/LingDong-/wenyan-lang/blob/master/documentation/API.md

**Comment by puchenhui** [comment]
> If you want to run the compiler by yourself, you can read this document https://github.com/LingDong-/wenyan-lang/blob/master/documentation/API.md

thanks,but page cannot be opened

**Comment by puchenhui** [comment]
> @antfu project is about ancient Chinese, reply is English, seems weird. I think you can：
> 
> ```
> 有一书简，名曰 ReadMe，汝可观之。或假以online ide试之。
> ```

吾乃略读ReadMe,但仍未解鄙人之惑。不知兄台用其方法可否实现？

**Comment by antfu** [comment]
> thanks,but page cannot be opened

Sorry the document name is recently updated, check https://github.com/LingDong-/wenyan-lang/blob/master/documentation/Compiler-API.md

**Comment by puchenhui** [comment]
> > thanks,but page cannot be opened
> 
> Sorry the document name is recently updated, check https://github.com/LingDong-/wenyan-lang/blob/master/documentation/Compiler-API.md

Ok，thank you very much

**Comment by kaiyuan01** [comment]
@puchenhui As Antfu suggested:

npm i
npm run build
npm t

**Comment by apologisesmile** [comment]
npm run build
