### ISSUE TITLE
Import module duplicately

### ISSUE THREAD

**Issue by cuixiping** [wenyan-lang/wenyan#420]
某經.wy
```
吾有一數。曰負一名之曰「負一」。
```

甲經.wy
```
吾嘗觀「「某經」」之書。
```

乙經.wy
```
吾嘗觀「「某經」」之書。
```

主程式.wy
```
吾嘗觀「「某經」」之書。
吾嘗觀「「甲經」」之書。
吾嘗觀「「乙經」」之書。
```

See the compile result of `主程式.wy`. You can see the whole content of `某經.wy` was inserted 3 times.

The module system can be improved to avoid the duplication.

**Comment by LingDong-** [comment]
Hi @cuixiping ,

I agree, and better import is indeed planned: #412

Although another problem with sharing modules just came to my mind: if one of those files modified things from imported module, the other files who imported the same module should not suffer from these (unexpected) modifications. So we'll have to "fork" a new version for it as soon as a file tries to modify its imported module. Lots of implementation details to think about :)

Thanks!

**Comment by cuixiping** [comment]
No need to consider the effects of modifying modules content. JS/ES/node modules also allow modifying sharing modules.
