### ISSUE TITLE
class, constructor and 'new' operator

### ISSUE THREAD

**Issue by cuixiping** [wenyan-lang/wenyan#426]
How to write with wenyan?

```
var obj = new Foo( );
var obj = new Foo( param );
```

```
實例「甲」。名之曰「乙」。
實例「甲」於「乙」。名之曰「丙」。
```

**Comment by LingDong-** [comment]
Hi, thanks for bringing this up. These will probably added along other OOP related functionalities that maps to JS's `Object.xx` etc, in the form of the standard library (e.g. `格物(經/書/學)`?)

**Comment by lymslive** [comment]
开个脑洞建议：
定义类

```
吾有一物，名之曰“类”，其形如下：....
// or
吾有一物，名之曰“类”，是“类”曰：…………此“类”之形也。
```

定义实例
```
吾有一物，名之曰“例”，其形如“类”。
```

单继承与多继承
```
吾有一物，名之曰“有为法”，其形如“梦幻泡影”。
吾有一物，名之曰“有为法”，其形如“露”，其形如“电”。
吾有一物，名之曰“有为法”，其形如“露”亦如“电”亦如“……”。

```

class is nothing more than object.

**Comment by antfu** [comment]
Duplicated #31
