### ISSUE TITLE
关于「为」关键字的写法

### ISSUE THREAD

**Issue by wglnngt** [wenyan-lang/wenyan#450]
「为」的常用繁体字有「為」和「爲」两种，有的输入法只能打出爲字，請作者將其加入關鍵字列表一下。謝謝。

**Comment by lymslive** [comment]
感觉新加的宏功能可以自行解决这个问题？
不过官方可以收集一下常见需求出一个“宏补丁”，给需要的用户择用。

**Comment by antfu** [comment]
Duplicated #185
