### ISSUE TITLE
Invite Wiki contribution

### ISSUE THREAD

**Issue by liyishuai** [wenyan-lang/wenyan#459]
To build a lively community, we should encourage people to contribute interesting although non-library code like #451.
Wiki seems a better place than issue tracker or pull requests for that.
Consider enabling Wiki write access to the public? [Docs here](https://help.github.com/cn/github/building-a-strong-community/changing-access-permissions-for-wikis).

**Comment by LingDong-** [comment]
Hi @liyishuai , thanks for bringing this up!

- I think the wiki is a great place for documenting the language. We can use it to build a handbook-like guide. However I'm not sure if we should allow random pieces of code to be added to it; If this is a common practice, could you please provide some examples?

- I totally agree that we should encourage people to share pieces of wenyan-lang code. It is a great way to grow the community. I'm considering making a site powered by Github Gist API, where users can write and submit bits of code, as well as browse and inspect code by other people. It could also function like a poor-man's CDN, solving the problem where many people have great ideas that might not fit into the standard examples/library, like you mentioned. I'll look into this, and probably make an announcement about it when I have more clues.

Thanks!

**Comment by liyishuai** [comment]
It might not be a common practice to include random code snippets in wiki, but I'd imagine a single page where people can add links to their wenyan gist or repo, with one-line introduction.

**Comment by antfu** [comment]
Thanks for the suggestion! We are now using the wiki pages. You can check it out on https://github.com/wenyan-lang/wenyan/wiki
