### ISSUE TITLE
How to Specify the Imported Module Path

### ISSUE THREAD

**Issue by lymslive** [wenyan-lang/wenyan#475]
# How to Specify the Imported Module Path

## Backgroud

Now `import` is supported in `wenyan`, but I cannot find how to specify custom
module path, and the explaination for standar path.

From the common habbit or knowledge there may be such default import path:

* `pwd` the current working direcotry where invoke `wenyan` command
* the location where the startup `.wy` script in.
* other built in search path or configed in some environment variable

The first tow paths may equal or not in some cases.

There may be complext case when nest import occurs, say execute `wenyan A.wy`,
where `A.wy` import `B.wy` and `B.wy` import `C.wy` etc. Then the relative to
current script may varis, sometimes raise confuse. In seldom cases, the `pwd`
may also changed if the imported modele can execute command like `cd`.

## Proposal Keyword

In wenyan-lang, we may call the place where put modle `藏经阁`, and define the
modle path by `藏经于`.

`吾藏经于` scoped current script, only effect current script when find
importing module. While `今藏经于` globally define the module path, can effect
any nest importing module afterward.

Maybe `今藏经于` is not perfectly opposite to `吾藏经于`. `吾藏经于` means I
put my own module in some favor place (folder). But think in `今藏经于` case,
the module is not put by me, that usuaslly put by others. So saying `闻藏经于` is
more accurate. However this introduct extrac keyword `闻`.

How will sound like to try comibe them , compare reading following phrase:

```
吾藏经于
今藏经于

今闻藏经于
吾将藏经于

吾闻藏经于
吾将藏经于
```

`将` in classic chinese not means `将来`(will), but means something like `拿来
做吧` (doing).

Which two express the module path better, or we only need one.

## Assumption Example

```
吾闻藏经于「「/opt/wenyan/lib」」
吾嘗觀「算經」之書。方悟「正弦」「餘弦」之義。
```

```
吾将藏经于「「./lib」」
// or equals to
// 吾将藏经于「「lib」」
吾嘗觀「算經」之書。方悟「正弦」「餘弦」之義。
```

Normally, the absolute path mainly used in global version of `藏经于`, and the
relative path mainly used if scoped version of `藏经于`. For exmaple a master
module which mange a bundle of sub-modules organized in sub-folder. The end
user only need to import the master modules, by specifing the global `藏经于`,
while the master module internally need scoped `藏经于` to import sub-module.

By the way, the argument feed to `藏经于` is literal string for system path, 
so should use double quote symbol, while the module followed by `吾尝观` more
like a namespace identifier, then should use single quote symbol.

Welcome discussion.

**Comment by LingDong-** [comment]
Good suggestion.

Currently users specify which paths to look at by supplying the `reader` function to the compiler. The main reason is that the compiler might be used in many different environments, e.g. browser, locally, etc. You can make it look in /lib or any folder if you prefer, similar in effect to putting them into $PATH. I don't think this should be a syntax within wenyan-lang though, because we would then limit the code to be only run-able on one platform.

However I think we can consider adding a syntax for specifying **relative** path. Currently the default `reader` looks in the cwd and one level down, but is of course not as ideal if the user has a complicated folder structure.

The term `藏经阁` has a Buddhist connotation though, I propose the more general `藏書樓` metaphor. 

```
吾嘗觀「乙」閣中「甲」之書。
吾嘗觀「丙」樓中「乙」閣中「甲」之書。
吾嘗觀「丁」園中「丙」樓中「乙」閣中「甲」之書。

```

Or we can drop the `園、樓、閣` and simply use `中` or `裡`. Somehow reminds me of `桃花塢裡桃花庵桃花庵裡桃花仙` :)

Thanks for bringing this up!

**Comment by lymslive** [comment]
Well, I not thought of browser at first, as I'm less farmiliar with that, I mainly thought wenyan-lang as a host script language alike python/perl/node. Node everionment has definitely some diffirence with browser.

I first thouht of `藏经阁` because I saw that many stdlib are named after `经`,  《易经》《算经》etc.

If we can limit the folder level, use `园、楼、阁` is nice. This solution is some like chinese number, named each unit `(个)十百千万`. So if only one level subfolder, say `某阁`, two level down say `某楼某阁`.

But in pratice, I doubt that it is still more handy using `path/to/subforder` string notation. When user give the subfolder arbitrarily name, it will not sound so nice modified by `园、楼、阁`.

**Comment by antfu** [comment]
@LingDong-  I have an idea that might make `reader` works universally. When we using browsers, there might be some modules available online requiring to be requested. Since we need to handle the `http` paths, then locals files are also accessible through `file://` scheme. I think we can use browsers `fetch` and `node-fetch` to make the path universal and do this trick. This also make the package free of `fs` dependence.

**Comment by lymslive** [comment]
You still not specify in current implement, what path will searched.
And if user want write module to be imported in others, where should put the imported script.

I tested the shipped example dir. 
Supported I clone down this repos in `~/downloads/github/wenyan-lang`

```
cd ~/downloads/github/wenyan-lang
~/downloads/github/wenyan-lang$ wenyan examples/import.wy
-- Output OK

~/downloads/github/wenyan-lang$ cd examples/
~/downloads/github/wenyan-lang/examples$ wenyan import.wy
--Output OK

~/downloads/github/wenyan-lang/examples$ cd
~$ wenyan downloads/github/wenyan-lang/examples/import.wy
--Output Error Msg Like Following:
Cannot import  helloworld
/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:36265
    for (var i = 0; i < txt.length; i++) {
                            ^

TypeError: Cannot read property 'length' of undefined
    at getImports (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:36265:29)
    at extractMacros (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:36357:17)
    at extractMacros (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:36368:28)
    at compile (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:1699:16)
    at getCompiled (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:2028:10)
    at exec (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:2119:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:1995:3)
    at __webpack_require__ (/usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:31:30)
    at /usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:95:18
    at /usr/local/lib/node_modules/@wenyanlang/cli/index.min.js:98:10
```

So, what the search rule? And the last error stack is not friendly for nomral user unless want debug.

Then I use locally built cli to run the example, another error raised.

```
lymslive@DESKTOP-KRJE2KE:~/downloads/github/wenyan-lang$ ./wenyan examples/helloworld+.wy
問天地好在。
問天地好在。
問天地好在。
lymslive@DESKTOP-KRJE2KE:~/downloads/github/wenyan-lang$ ./wenyan examples/import.wy
/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:37207
    if (imports[i] in lib[lang]) {
                   ^

TypeError: Cannot use 'in' operator to search for '算經' in undefined
    at extractMacros (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:37207:20)
    at compile (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:1728:16)
    at getCompiled (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:2121:10)
    at exec (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:2212:16)
    at Object.<anonymous> (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:2088:3)
    at __webpack_require__ (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:31:30)
    at /home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:95:18
    at /home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:98:10
    at webpackUniversalModuleDefinition (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:4:20)
    at Object.<anonymous> (/home/lymslive/downloads/github/wenyan-lang/dist/cli/index.min.js:11:3)
lymslive@DESKTOP-KRJE2KE:~/downloads/github/wenyan-lang$ ./wenyan -v
0.2.0
lymslive@DESKTOP-KRJE2KE:~/downloads/github/wenyan-lang$ ll ./wenyan
lrwxrwxrwx 1 lymslive lymslive 21 Jan  7 21:38 ./wenyan -> dist/cli/index.min.js*
```

**Comment by LingDong-** [comment]
Hi @lymslive , The current search rule is to search the [Current Working Directory](https://en.wikipedia.org/wiki/Working_directory) and one level down. But the import mechanism will soon enough change to something better, see #499 ,  so stay tuned!

Your second issue with locally built CLI indicates that the stdlib is not loaded, and seems to be reminiscent of this issue: #481

Will look into it, thanks a lot for bringing this up!

**Comment by lymslive** [comment]
Thanks, I see.
But one question. "one level down" means any subdirectory, something like `./*/module.wy` ?

At first glance it may be convienent, because user may want to put his module in a subdirectory in `lib` or `libs` or `module` or `modules` even or `include`, and even more capital variants, this rule save the tedious work to specify the subdirectory.

But here are two points.
1. Efficiency, if current directory has too many subdirectory, this may ignore in common case.
2. Misleading. For example, I make a copy of `lib` named `bak` or `.bak`(hidden), I expect to import the module in `./lib`, but may import the one in `./bak`, especailly `bak` normally sorted before `lib`.

So I think `any subdirectory` may not ideal solution. If I misunderstood, correct me.

**Comment by LingDong-** [comment]
@lymslive You're correct. But this is only the default behavior just for convenience, you can specify exactly how you would like to load modules by modifiying the `reader` option to `parser.compile`.

However, the mechanism is going to welcome a big change in PR #499 . So the all issues you mentioned will probably not be a problem once that's done :)

**Comment by lymslive** [comment]
But for normal user beyond js developer, he/she may refuse to modify source, just rely on cli for example. You'd better provide a configurable way for cli.
I'll be honoured if you consider my suggestion/worry when developing #499

**Comment by antfu** [comment]
I think the problem is resolved. Please check out #499 and #519 for more details.
