### ISSUE TITLE
吾初涉编程之领域，但尤喜此语言。有几问望解答。

### ISSUE THREAD

**Issue by haonanq666** [wenyan-lang/wenyan#482]
有几问求高人赐教。其一，如何书注释？其二，可否使用指针以动态管理内存？其三，可有开发独立、线下、国风样貌IDE之打算？

文末斗胆提议：术收参数之言语甚繁。与其多次书「曰」，何不省略？如：「欲行此术，必先得二数「甲」、「乙」」或「欲行此术，必先得一数「甲」、一言「乙」」。

**Comment by lymslive** [comment]
`、`是被编译器忽略的。
但标识符既然有 `「」`，并列标识符也许可行。

**Comment by LingDong-** [comment]
Hi @haonanq666 , good questions!

> 如何书注释

`注曰`/`疏曰`/`批曰`, See README:
https://github.com/LingDong-/wenyan-lang#comments

> 可否使用指针以动态管理内存

Currently, no. In the future, maybe not.

> 可有开发独立、线下、国风样貌IDE之打算？

With [electron](https://electronjs.org/), it should be straightforward to port the web IDE to native software, and styling could be easily customized with CSS. However, I doubt the user experience would ever be comparable to Sublime, VSCode etc, so using wenyan-lang plug-ins to these already-well-polished editors might be a better solution if you would like to edit offline.

You can check out the IDE plugins here:
https://github.com/LingDong-/wenyan-lang#text-editor-plugins
