### ISSUE TITLE
简体秘笈试行

### ISSUE THREAD

**Issue by lymslive** [wenyan-lang/wenyan#509]
我尝试了一下，感觉大致可行。

`lib/简体秘笈.wy`如下：

```
或云『数』蓋謂『數』
或云『阴』蓋謂『陰』
或云『阳』蓋謂『陽』
或云『为』蓋謂『為』
或云『术』蓋謂『術』
或云『谓』蓋謂『謂』
或云『于』蓋謂『於』
或云『书』蓋謂『書』
或云『尝』蓋謂『嘗』
或云『观』蓋謂『觀』

或云『，』蓋謂『。』
或云『：』蓋謂『。』
或云『；』蓋謂『。』
或云『？』蓋謂『。』
或云『！』蓋謂『。』
或云『…』蓋謂『。』
或云『—』蓋謂『。』
```

`helloworld-chs.wy` 如下：

```
吾嘗觀『简体秘笈』之书。

吾有一数，曰三，名之曰「甲」。
为是「甲」遍：
        吾有一言，曰『問天地好在』，书之。
        吾有一言，曰『问天地安好』？书之。
        ————————
        吾有一言，曰『为术数阴阳』，书之。
        吾有一言，曰『為術數陰陽』？书之。
        ……
云云！
```

运行结果：

```
問天地好在
问天地安好
为术数阴阳
為術數陰陽
問天地好在
问天地安好
为术数阴阳
為術數陰陽
問天地好在
问天地安好
为术数阴阳
為術數陰陽
```

补充说明：
“嘗觀……之書” 导入语句须用繁体关键字，不过“書”可以立即改成简体也行。
标点符号只是替换为忽略的字符，参考 #462 

我的观点：
现代汉语与简体字是既成事实，也算是古汉语的自然延续。
wenyan-lang 的内核支持用繁体，显得有文化底蕴，人家谈论起来也只有敬意。
但为免国人敬而远之，以及将来有可能实用的梦想，简体字还是应该支持的。

**Comment by LingDong-** [comment]
Looks good!
However I don't think we should put it in the stdlib though. It would better exist as a (potentially popular) 3rd-party library for those who need it. As I've explained multiple times, I think the disadvantages of supporting character variations outweighs the advantages, but of course, that's why we have macros so people don't have to agree with my philosophy :)

**Comment by LingDong-** [comment]
@lymslive 

```
吾嘗觀「汉字简化方案」之書。
```

**Comment by antfu** [comment]
Hi @lymslive. The package management is ready to use, #510! And I think this library can be very helpful for people who need it. Can you consider publishing a package for this? The detailed instructions can be found in [文淵閣總目](https://github.com/wenyan-lang/wyg-registry). Thanks!

**Comment by lymslive** [comment]
我看到了。多谢。
我个人还是喜欢四个字的，故取名为“简体秘术”了。

另外，我觉得 `wyg-registry` 是个动作，而“文淵閣總目”是名词，是否用“文淵閣编目”好些？@LingDong-

**Comment by antfu** [comment]
`registry` here is a noun means `登記處` or `註冊處` in modern Chinese. (please note it's not `register`). A side note, npm also called itself ["the largest software registry"](https://docs.npmjs.com/about-npm/)

**Comment by lymslive** [comment]
@antfu 好吧，我一开始理解错了，以为是一个个提交注册的，原来是直接登记全部啊。
然而我感“编目”既可作动词，也可作名词。

**Comment by lymslive** [comment]
我将破折号改为用于注释了，不单是忽略破折号，还忽略两个破折号之间的文本。
就像 mysql 用两横线 `--` 表示尾注释。
不过 wenyan-lang 是行间注释，必须首尾各一个破折号，就如 C 注释 `/* */` 一样。

安装命令：
```
npm i -g @wenyanlang/wyg
wyg i 简体秘术
```

源代码在 https://github.com/lymslive/wyg-packages/tree/jiantihua
欢迎有兴趣或简体执念的朋友试用。此 issue 可关闭了。
