### ISSUE TITLE
不能行「書之」於「術」中

### ISSUE THREAD

**Issue by GLanguage** [wenyan-lang/wenyan#521]
## 不能行「書之」於「術」中

予試行
```
⋯⋯
吾有一術。名之曰「所為」。欲行是術。必先得一言。曰「所得」。乃行是術曰。
    夫「所得」。書之。
是謂「所為」之術也。
```
然編譯得
```javascript
⋯⋯
var 所為 = () => 0;
所為 = function(所得) {
  var _ans5 = 所得;
  console.log(_ans1, _ans2, _ans3, _ans4, _ans5);
}
```
予欲書「所得」，然其試書另四值並「所得」。該四值曾用於前，其作用域未及此矣。運行得
```
ReferenceError: _ans1 is not defined
```
懲此矣。

**Comment by antfu** [comment]
Can you share the rest of your code? The example given seems to work fine for me.
![image](https://user-images.githubusercontent.com/11247099/72201245-e1685b80-348c-11ea-8c1f-ad81fe924bbc.png)

**Comment by GLanguage** [comment]
吾甚難矣。
Now it seems to work fine for me too.
Maybe there is something wrong with my compiler a few minutes ago.

**Comment by laipuran** [comment]
It's&nbsp;A&nbsp;bit&nbsp;difficult~

---原始邮件---
发件人: &quot;GLanguage&quot;<notifications@github.com&gt;
发送时间: 2020年1月11日 16:05:47
收件人: &quot;wenyan-lang/wenyan&quot;<wenyan@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [wenyan-lang/wenyan] 不能行「書之」於「術」中 (#521)


 
不能行「書之」於「術」中
 
予試行
 &#x22EF;&#x22EF; 吾有一術。名之曰「所為」。欲行是術。必先得一言。曰「所得」。乃行是術曰。     夫「所得」。書之。 是謂「所為」之術也。  
然編譯得
 &#x22EF;&#x22EF; var 所為 = () =&gt; 0; 所為 = function(所得) {   var _ans5 = 所得;   console.log(_ans1, _ans2, _ans3, _ans4, _ans5); }
 
予欲書「所得」，然其試書另四值並「所得」。該四值曾用於前，其作用域未及此矣。運行得
 ReferenceError: _ans1 is not defined  
懲此矣。
 
&mdash;

**Comment by wglnngt** [comment]
Maybe you used some unnamed vairants before the showing code. Such as "夫……", "加/減/乘/除……以……". If they ware defineded(by translation wenyan code) but not used, when you typing "書之", they will be outputed also. If you want to disable the other unnamed variants before you output, you can type "噫。" before you using wanted unnamed variants.

**Comment by SketchySketch** [comment]
The `書之` function will accept all parameters in the variable stack. Before `書之` you should discard everything by `噫`.
