### ISSUE TITLE
无法输出

### ISSUE THREAD

**Issue by chuang-zhi** [wenyan-lang/wenyan#522]
安装后无法输出

**Comment by chuang-zhi** [comment]
![image](https://user-images.githubusercontent.com/49262488/72201596-bc75e780-3490-11ea-991a-60754e058026.png)

![image](https://user-images.githubusercontent.com/49262488/72201600-c4358c00-3490-11ea-88ed-d5db9c92dd3b.png)

**Comment by chuang-zhi** [comment]
本人正在写一个Windows本地IDE

**Comment by LingDong-** [comment]
Hi @chuang-zhi , Could you please provide more context, i.e. what version of `node`, what version of `wenyan`, etc. What happens when you run other examples? Could you please try `wenyan -c D:\readme.wy` and see what the compiled JavaScript is like? Thanks!
Good luck with Windows IDE, looking forward to it!

**Comment by chuang-zhi** [comment]
OK

**Comment by chuang-zhi** [comment]
```
node:v13.0.6.0
wenyan:0.2.4
```

**Comment by chuang-zhi** [comment]
我已经尝试使用了`wenyan -c D:\readme.wy`，但没有文件输出，在cmd也没有任何输出，请问如何解决？

**Comment by chuang-zhi** [comment]
这是Bug吗？

**Comment by chuang-zhi** [comment]
我的node是免安装的，这有影响吗？

**Comment by antfu** [comment]
@chuang-zhi does there any outputs when running `wenyan -v`?

**Comment by chuang-zhi** [comment]
@antfu 有输出`0.2.4`，但运行`.wy`的代码无输出

**Comment by antfu** [comment]
Can you move the readme.wy file to the current and run `wenyan -c readme.wy`. Wonder if that would work.

**Comment by chuang-zhi** [comment]
@antfu No...

**Comment by antfu** [comment]
Maybe it's not a problem from wenyan. Can you try it on a normal Node(installer version)? Thanks.

**Comment by statementreply** [comment]
Is your readme.wy encoded in UTF-8? I believe that the wenyan cli doesn't work for other text encodings.

**Comment by chuang-zhi** [comment]
> Is your readme.wy encoded in UTF-8? I believe that the wenyan cli doesn't work for other text encodings (GBK, BIG-5, etc.).

Oh, thanks.

**Comment by chuang-zhi** [comment]
问题已解决。
