### ISSUE TITLE
Netlify not deploying

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/wenyan#531]
Seem Netlify not deploying even for master branch (the IDE is not updated as well)

![image](https://user-images.githubusercontent.com/11247099/72222682-8c1e6e00-35a2-11ea-974f-c4ac360ad97e.png)

Maybe it's due to it refers to the old repo or somehow.

**Comment by LingDong-** [comment]
You're right, I now fixed it to link to the new site, thanks for pointing out the problem!
