### ISSUE TITLE
When using in object, "昔之" compiles in a weird way

### ISSUE THREAD

**Issue by Fros1er** [wenyan-lang/wenyan#541]
`昔之「精衛」之「名」者。曰一。` compiles to `精衛[名 - 1] = 1;`

Actually the code doesn't makes sense, but I'm wondering why `[名 - 1]` comes out.

**Comment by antfu** [comment]
Array index in Wenyan starts from 1.

https://github.com/wenyan-lang/wenyan#containers

**Comment by Fros1er** [comment]
> Array index in Wenyan starts from 1.
> 
> https://github.com/wenyan-lang/wenyan#containers

Do you mean `昔之「精衛」之「名」者。曰一。` equals to `昔之「精衛」之「名」者。今一是矣。` ?

By the way, It seems impossible to express
 ```
var 精衛 = {}
精衛 = { 名: "女娃" }
var 元 = "名"
精衛[名] = "精衛"
```
, as 
```
吾有一物。名之曰「精衛」。其物如是。
	物之「「名」」者。言曰「「女娃」」。
是謂「精衛」之物也。
吾有一言。 曰「「名」」。名之曰「元」。
昔之「精衛」之「名」者。今「「精衛」」是矣。
```
compiles to
```
var 精衛 = {}
精衛 = { 名: "女娃" }
var 元 = "名"
精衛[名 - 1] = "精衛"
```
.

**Comment by LingDong-** [comment]
Hi @Fros1er , thanks for bringing this up.

Currently it is not possible (without hacks) to use dynamically generated property keys to index objects. See this https://github.com/wenyan-lang/wenyan/issues/388#issuecomment-568844728 and https://github.com/wenyan-lang/wenyan/issues/532#issuecomment-574287294 for reasons & details, thanks!

**Comment by cuixiping** [comment]
@stevefan1999-personal 
You should use like this
```
昔之「精衛」之「「名」」者。曰一。
```

**Comment by MagicLu550** [comment]
wenyan_jvm is implemented by using ArrayUtils written by itself to make type judgments. No extra -1 ...
`` groovy
static def getIndex (index) {
         if (index instanceof Integer) return (Integer) index-1
         return index
     }
`` `
Comparison sloppy

**Comment by LingDong-** [comment]
I suppose for JavaScript we can also hijack `Array.prototype` to make it start indexing from 1, or add a getter to it like @MagicLu550 's example etc. Sounds a bit hacky, but might worth investigating :)

**Comment by Fros1er** [comment]
A more hacky way is using
```
function(dict){
    return function(key){
        return dict['key'];
    }
}
```
.
But I'm not sure if it's appropriate to put it in stdlib.

**Comment by cuixiping** [comment]
```
function(dict){
    return function(key){
        return dict['key'];
    }
}
```

@Fros1er Your code is a bug. Do you mean `dict[key]`? It does nothing improvement.

Currently, `A之B` is translated to `A[B]` or `A[B-1]`.
Alternatively, translate `A之B` to similar `getMember(A)(B)`, and add a `getMember` function to the compile result. But it's not good enough.

If use different wenyan syntax for those 2 cases, there may be something like:

```
A之B      // A[B]
A之第B    // A[B-1]
```

**Comment by MagicLu550** [comment]
> ```
> function(dict){
>     return function(key){
>         return dict['key'];
>     }
> }
> ```
> 
> @Fros1er Your code is a bug. Do you mean `dict[key]`? It does nothing improvement.
> 
> Currently, `A之B` is translated to `A[B]` or `A[B-1]`.
> Alternatively, translate `A之B` to similar `getMember(A)(B)`, and add a `getMember` function to the compile result. But it's not good enough.
> 
> If use different wenyan syntax for those 2 cases, there may be something like:
> 
> ```
> A之B      // A[B]
> A之第B    // A[B-1]
> ```

I think that you can make type judgments on variables, after all, only integer types need -1

**Comment by Fros1er** [comment]
> ```
> function(dict){
>     return function(key){
>         return dict['key'];
>     }
> }
> ```
> 
> @Fros1er Your code is a bug. Do you mean `dict[key]`? It does nothing improvement.
> 
> Currently, `A之B` is translated to `A[B]` or `A[B-1]`.
> Alternatively, translate `A之B` to similar `getMember(A)(B)`, and add a `getMember` function to the compile result. But it's not good enough.
> 
> If use different wenyan syntax for those 2 cases, there may be something like:
> 
> ```
> A之B      // A[B]
> A之第B    // A[B-1]
> ```

It should be `dict[key]`.

It's a function actually, and it only works for dict. 
For example, when `「甲」`is a dict and the function is named `「取物」`, `施「取物」於「甲」。於「乙」。` returns `甲[乙]`. So it has nothing to do with `「甲」之「乙」`.

**Comment by Fros1er** [comment]
> I think that you can make type judgments on variables, after all, only integer types need -1

I'm not sure about that. I don't use intenger as keys, but dict[1] makes sense(I tried in chrome's devtool). 
And I think when 甲 is a dict, `「甲」之一` means `甲[1]` instead of `甲[0]`.

**Comment by MagicLu550** [comment]
> > I think that you can make type judgments on variables, after all, only integer types need -1
> 
> I'm not sure about that. I don't use intenger as keys, but dict[1] makes sense(I tried in chrome's devtool).
> And I think when 甲 is a dict, `「甲」之一` means `甲[1]` instead of `甲[0]`.

I'm curious about the allusion to use one instead of zero ...

**Comment by cuixiping** [comment]
```
探「囊」取「物」
「囊」中取「物」
```

:smiley:
