### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/wenyan#542]
As I am trying to read the tokenize/tsc parts and trying to do some changes/experiments. I found myself struggling on finding the token names and what's going on. 

I would propose we switch to Typescript for better DX. XD
Yes, I know this is huge. But please kindly consider this.

Benefits
- Strong types, fewer bugs.
- Better editor support, make easier for contributors to help
- Exported typing files for packages. ( compiles or other stuff get a lot of options, with typing file, editors can do auto-complete and inline documentation, and even for js users)
- Use newer js features and transpile to the current env.
- For the benefits of Typescript, I can talk for a whole day. You can also check out https://medium.com/@jtomaszewski/why-typescript-is-the-best-way-to-write-front-end-in-2019-feb855f9b164

Cost
- Toolings. Since we are already using webpack, it's fairly simple to integrate. I can handle that.
- Some code refactoring.
- A little learning but not steep

I am doing to experiment on a branch. Let me know what you think before I continue. Thanks!

**Comment by LingDong-** [comment]
I think this is a good proposal, and I’ve heard a lot of great things about Typescript. However I don’t know typescript (at all). I think it would be better if I first secretly learn/try out Typescript for a week or two, and make the decision then.

Another solution, or rather something I should do regardless of the switch, is to comment my code and better name the variables :P .

**Comment by antfu** [comment]
Typescript is a superset of Javascript. Which means all javascript is valid typescript. Without only a few types notations, it's basically the morden js. (and the type inference works great). Please do check it out! 😄
