### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/wenyan#559]
https://opencollective.com/

I am not sure whether this project should accept donations. But open collective does offer this nice badges :)

*Screenshot from Vue.js*
![image](https://user-images.githubusercontent.com/11247099/72645252-17b14980-396b-11ea-93f3-cf1ae1373b89.png)
https://opencollective.com/vuejs/contributors.svg?width=890

**Comment by LingDong-** [comment]
I think we can DIY the little icons using github API
https://api.github.com/repos/wenyan-lang/wenyan/contributors
We only have 44 contributors in total though, that's like just over 1 row. Won't be nearly as spectacular as the screenshot :P

I'm not familiar with how opencollective or donations works, from what I understand, people give us $$$ to have us put their logo in our README? Sounds like a good deal, what would be your opinion?

**Comment by antfu** [comment]
> people give us $$$ to have us put their logo in our README?

Basically, yes. People give money to thank you and support your work. And you can promise something for financial contributors in return (exclusive contents, priority service or anything you want. But people are doing Backers/Sponsors logo presentation mostly).

You can check the offers other projects made for different tiers. Here are some examples
https://opencollective.com/webpack
https://opencollective.com/vuejs
https://opencollective.com/nest

IMO, financial support is always great for open source project to substance and grow :) Anyway, the decision is up to you.

> We only have 44 contributors in total though

That's actually quite a lot. The badges will auto-scale to adopt the numbers of contributors. 
![image](https://user-images.githubusercontent.com/11247099/72660739-b641b700-3a0c-11ea-8e2f-460f472a0523.png)

**Comment by LingDong-** [comment]
@antfu  I took a closer look at open collective and I think it's a neat idea, let's do it!

One thing that doesn't seem to be clear from the website though, how is the donated money distributed? Are they equally distributed among all contributors? Weighted based on number of commits? Or do contributors request sums they think themselves deserve every time they make contributions? Or do we have to devise our own strategy?

**Comment by antfu** [comment]
I think it's up to you. As far as I know, It's kinda like a repository of money, for most of time, the money will be hold in open collective. And when you have some cost (salaries, bonuns or whatever you want) you can withdraw from it. All the incomes and outcomes are transparent to everyone. Guess it's what the open means :)

**Comment by antfu** [comment]
Here, for example
https://opencollective.com/vuejs/expenses

**Comment by LingDong-** [comment]
Okay! made an account

https://opencollective.com/wenyan-lang

Trying to figure out next steps...

P.S. I'm thinking we divide donation into different budgets for regular contribution & for special things, we can come up with some plans... of course all depends on people actually donating XD

**Comment by LingDong-** [comment]
[![OpenCollective](https://opencollective.com/wenyan-lang/backers/badge.svg)](#backers) 
[![OpenCollective](https://opencollective.com/wenyan-lang/sponsors/badge.svg)](#sponsors)
Couldn't figure out how to generate the matrix of heads though :P

**Comment by antfu** [comment]
Got to wait a couple hours until it's updated

**Comment by antfu** [comment]
It would be in this url https://opencollective.com/wenyan-lang/contributors.svg?width=890&button=false

When it's ready, we could add the following md to readme and wiki.

```md
## Contributors

### Code Contributors

This project exists thanks to all the people who contribute. [[Contribute](CONTRIBUTING.md)].
<a href="https://github.com/wenyan-lang/wenyan/graphs/contributors"><img src="https://opencollective.com/wenyan-lang/contributors.svg?width=890&button=false" /></a>

### Financial Contributors

Become a financial contributor and help us sustain our community. [[Contribute](https://opencollective.com/wenyan-lang/contribute)]

#### Individuals

<a href="https://opencollective.com/wenyan-lang"><img src="https://opencollective.com/wenyan-lang/individuals.svg?width=890"></a>

#### Organizations

Support this project with your organization. Your logo will show up here with a link to your website. [[Contribute](https://opencollective.com/wenyan-lang/contribute)]

<a href="https://opencollective.com/wenyan-lang/organization/0/website"><img src="https://opencollective.com/wenyan-lang/organization/0/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/1/website"><img src="https://opencollective.com/wenyan-lang/organization/1/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/2/website"><img src="https://opencollective.com/wenyan-lang/organization/2/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/3/website"><img src="https://opencollective.com/wenyan-lang/organization/3/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/4/website"><img src="https://opencollective.com/wenyan-lang/organization/4/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/5/website"><img src="https://opencollective.com/wenyan-lang/organization/5/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/6/website"><img src="https://opencollective.com/wenyan-lang/organization/6/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/7/website"><img src="https://opencollective.com/wenyan-lang/organization/7/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/8/website"><img src="https://opencollective.com/wenyan-lang/organization/8/avatar.svg"></a>
<a href="https://opencollective.com/wenyan-lang/organization/9/website"><img src="https://opencollective.com/wenyan-lang/organization/9/avatar.svg"></a>
```

**Comment by antfu** [comment]
> So complex! I'm basically given a blank page with no clue what to do and the docs is some business terminology that I don't quite understand... Can I add you as an admin somehow XD 

Oh Sure! No problem!

**Comment by LingDong-** [comment]
@antfu thanks, I just sent you an invite on open collective

**Comment by antfu** [comment]
@LingDong- Ok, I see. We were using the wrong type of open collective (not organization). I have renamed the old one to [wenyan-lang-org](https://opencollective.com/wenyan-lang-org) (and probably should be removed) and created a new collective linked to the repo. Have sent you the invitation.

**Comment by LingDong-** [comment]
👍 No wonder I couldn't figure out how to use it :P
I just joined the new collective and it looks good

**Comment by antfu** [comment]
Maybe we could delete the org one then. 

I draft some simple tiers. You can check them out and edit them if needed.

**Comment by LingDong-** [comment]
LGTM, feel free to announce, thanks!

**Comment by antfu** [comment]
The badges are ready. I am going to update the README

**Comment by antfu** [comment]
Updated. Btw I have noticed you are using different email addresses for committing and it seems like the local commits are not counting to your account. Not sure if it matches your expectations. If not, you may link your email for local commit to Github. [Guide here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-on-github)

<sub>Yes I am feeling unworthy to being the first of the list. Especially it's because I have committed a lot of verbose changes 😂😂</sub>

**Comment by LingDong-** [comment]
It looks great!

> local commits are not counting to your account

I discovered so too and have already corrected my email recently. But github is refusing to backtrack all the previous commits. I tried this https://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails just now, and apparently all it does is doubling the number of total commits... now we have 1613! So I think it's a good time for me to stop fooling around with git...

Congrats on being on the top of the list! I think you totally deserve it. The language can't thank you enough for your awesome work! 🎉

**Comment by antfu** [comment]
> now we have 1613!

Wow!... All the commits are duplicated. I was thinking you can do you a force push, but it will make existing PRs and forks invalid. Do you want me to revert the modification?

> Congrats on being on the top of the list! I think you totally deserve it. The language can't thank you enough for your awesome work! 🎉

Thank you for your awesome work and allowing me to do so many things! It's my great honor to be the team and help out. 😁

**Comment by LingDong-** [comment]
> Do you want me to revert the modification?

Yes please. I was thinking about doing so myself but had an ominous feeling that I'm going to blow it up again :P

**Comment by antfu** [comment]
It's done :). Maybe I could do some research to see if GitHub can backtracking the commits later.

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/72744796-3a509600-3be9-11ea-9105-3a56568729b0.png)

That's sad. 😥 Actually I have noticed that right at the beginning of discovering this repo. I didn't mention that because I thought it will be kinda rude. Sorry, I should tell you much earlier.
