### ISSUE TITLE
Is there a way to access the error variable in catch statement?

### ISSUE THREAD

**Issue by zxch3n** [wenyan-lang/wenyan#566]
For example, I may need to print the error information.

```javascript
try {
	throw new Error();
} catch (e) {
	console.log(e.msg)
}
```

In the current design, however, I find no way to access the value of `e`.

**Comment by LingDong-** [comment]
Hi @zxch3n, thanks for bringing this up! Currently retrieving the name of the error is supported. For example:

```
姑妄行此。
	嗚呼。「「滅頂」」之禍。
如事不諧。不知何禍歟。名之曰「奇禍」。
	注曰「「變數「奇禍」所謂者。禍之名也」」
乃作罷。
```

If you would like to print extra associated error messages, one simple way would be to concatenate the name of the error with the error message, delimited by a special symbol, which you can then use in the catch clause to split them.

You may also use the name as an error code, and use an object to map the code to the message. For example:

```
吾嘗觀「格物」之書。方悟「取物」之義。

吾有一物。名之曰「釋禍」其物如是。
	物之「「error-code-001」」者。言曰「「天降橫禍。無可禳解」」
	物之「「error-code-002」」者。言曰「「嗚呼哀哉。伏维尚飨」」
是謂「釋禍」之物也。

姑妄行此。
	嗚呼。「「error-code-001」」之禍。
如事不諧。不知何禍歟。名之曰「奇禍」。
	施「取物」於「釋禍」於「奇禍」。書之。
乃作罷。
```

But if possible, I would suggest leveraging the 豈⋯⋯之禍歟 statement to catch specific errors.

Hope this helps!

**Comment by antfu** [comment]
@LingDong- The current error handling system only uses `.name`. For errors thrown by js itself/other modules, there are many fields are useful for debugging. `message` `trace` are common ones for example.

I think maybe we could expose the entire Error object in `不知何禍歟。` and let people take what they want.

For example

```wenyan
姑妄行此。
	嗚呼。「「事不關心」」之禍。
如事不諧。
	不知何禍歟。書之。
乃作罷。
```
Compiles to 
```js
try {
    var _rand1 = new Error();
    _rand1.name = "事不關心";
    throw _rand1;
} catch (_rand2) {
    var _ans1 = _rand2.name;
    console.log(_ans1);
}
```
Proposaled to
```js
try {
    var _rand1 = new Error();
    _rand1.name = "事不關心";
    throw _rand1;
} catch (_rand2) {
    console.log(_rand2);
}
```

And we may have usages like this
```wenyan
姑妄行此。

	嗚呼。「「事不關心」」之禍。
    
如事不諧。不知何禍歟。名之曰「奇禍」。
    
    施「取物」於「奇禍」於「其名」。書之。 // for error.name
    施「取物」於「奇禍」於「其言」。書之。 // for error.message
    
乃作罷。
```
(and in this way, we may need to hijack the Error prototype or the `取物` logic)

**Comment by LingDong-** [comment]
@antfu I think this proposal totally makes sense. I think if this is the case, we should also push the error object onto the variable stack in 豈⋯⋯之禍歟 clause just like in 不知何禍歟 to be consistent.

I don't think prototype hijacking or 取物 hijacking is required. We can simply inject the fields into the error object the very moment it is caught. So source code probably something like:

```js
var r = this.randVar();
js += `}catch(${r}){${r}['名']=${r}.name; ${r}.['文']=${r}.message; ${r}.['蹤']=${r}.trace;`;  
strayvar.push(r);
```

I think the user will not be able to tell the difference. They can even throw the error again. What do you guys think?

**Comment by zxch3n** [comment]
@LingDong- @antfu Thank you! Pushing the error object to the stack is all I need.

**Comment by antfu** [comment]
> So source code probably something like

I am concerned about it being a little bit verbose. I think the prototype solution is more elegant on this.

Just adding this 3 lines and all the Error object has the `名` `文` `蹤`. We already have the "polyfill lib" for python and ruby, I think it's reasonable to the the "js lib" prepped. (We can also check the asc for error syntax usage, add the polyfill only when the error handling is used. This can also apply to other features. aka `a la carte`)

```js
Error.prototype.__defineGetter__('名', function () { return this.name });
Error.prototype.__defineGetter__('文', function () { return this.message });
Error.prototype.__defineGetter__('蹤', function () { return this.trace });
```

Then you can access the field by in JS
```js
err.名
err.文
err.蹤
```

------------

For the `取物` part, I think `施「取物」於「奇禍」於「「名」」。書之。` is not very ideal for reading and understanding. The syntax for getting attributes is already been discussed in #541. Wondering if we have any plan to support this? Thanks.

**Comment by LingDong-** [comment]
Hey @zxch3n @antfu,

Support for error objects is now added; alias for `RangeError` `TypeError` etc. is also added.

Error objects are pushed onto the stack for each `豈⋯⋯之禍歟` and `不知何禍歟`, and their fields can be accessed using `之「「名」」/之「「文」」/之「「蹤」」`. If you don't need the objects themselves, you need to discard them using `噫`.

Alias: `SyntaxError->法  RangeError->逾界  TypeError->異類   ReferenceError->虛指`


See commit: 8bf7e0af28b8d6a376c9536843d672e9f39809a1

Example:

```
姑妄行此。
	嗚呼。「「滅頂」」之禍。

如事不諧。豈「「虛指」」之禍歟。名之曰「禍」。
	夫「禍」之「「名」」。書之。
	夫「禍」之「「文」」。書之。
	夫「禍」之「「蹤」」。書之。
	吾有一言。曰「「本無此物。奈何用之」」。書之。

豈「「文法」」之禍歟。名之曰「禍」。
	吾有一言。曰「「不合文法。不通之甚」」。書之。

豈「「異類」」之禍歟。
	噫。吾有一言。曰「「物各其類。豈可混同」」。書之。

豈「「滅頂」」之禍歟。
	噫。吾有一言。曰「「嗚呼哀哉。伏维尚飨」」。書之。

不知何禍歟。名之曰「奇禍」。
        吾有一言。曰「「人坐家中。禍從天降」」。書之。
乃作罷。
```


Maybe next step would be to optionally allow defining the `message`/`文` field.

Let me know what you think or if you find an issue with the implementation! Thanks.

**Comment by LingDong-** [comment]
Two new features added to catch grammar: f6f34196649578d932a9182bd40e178f3c0ae7ee

1. Error can optionally have messages in addition to their names. Achieved by immediately following `之禍` with `曰「「...message here...」」` They can then be accessed with `「禍」之「「文」」` in catch.

```
嗚呼。「「事不關心」」之禍。曰「「事不關心。關心者亂」」
```

2. `噫` is no longer required to discard the error object. Simply by not using `名之曰「禍」` will have the error object ignored, similar to `catch{`. To get the error object, follow `...之禍歟/不知何禍歟` immediately with `名之曰「禍」`, similar to `catch(禍){`. (See discussion https://github.com/wenyan-lang/wenyan/commit/8bf7e0af28b8d6a376c9536843d672e9f39809a1#r37358115)

```
姑妄行此。
    嗚呼。「「事不關心」」之禍。曰「「事不關心。關心者亂」」
如事不諧。豈「「虛指」」之禍歟。
    吾有一言。曰「「本無此物。奈何用之」」。書之。
豈「「文法」」之禍歟。名之曰「禍」。
    夫「禍」之「「蹤」」。書之。
    吾有一言。曰「「不合文法。不通之甚」」。書之。
不知何禍歟。名之曰「禍」。
    夫「禍」之「「名」」。書之。
    夫「禍」之「「文」」。書之。
乃作罷。
