### ISSUE TITLE
Is there a way to import npm/pip module?

### ISSUE THREAD

**Issue by TongChia** [wenyan-lang/wenyan#567]
是我不知道还是wenyan-lang无此功能？
如果要在具体的项目中使用，势必会用到大量第三方依赖。求告知方法🙏

**Comment by antfu** [comment]
Hi @TongChia! If you want to use the existing js/python modules, you can use this hack for now:

```wenyan
吾有一言。曰「x=>require(x)」。名之曰「取經」。

施「取經」於「「fs」」。名之曰「檢索」。
```

Or you can try the native package manager [wyg](https://github.com/wenyan-lang/wyg) built for wenyan-lang. It doesn't have too many packages yet. It will be awesome if you are also interested in creating one. :)

**Comment by akira-cn** [comment]
有一个hack方式可以嵌入任意的JS代码：

```
施「undefined;// hack

// 这里可以写任意JS

void」於零。
```

这段代码编译后结果是：

```js
const _ans1 = undefined; // hack

// 这里可以写JS

void(0);
```
