### ISSUE TITLE
Consider using traditional character ‘雲雲‘instead of ‘云云’keyword

### ISSUE THREAD

**Issue by XingZiLong** [wenyan-lang/wenyan#579]

**Comment by XingZiLong** [comment]
As I can’t  type ‘云云’ on traditional Chinese keyboard but other keyword ARE traditional characters, I found it difficult to switch between two very different keyboards all the time.

**Comment by XingZiLong** [comment]
I’m also considering about ‘\n’, which is not a Chinese character. Maybe we can say 「換行」instead of a letter, and that will make the code more beautiful. We can do the same thing to the errors(ReferenceError etc.).

**Comment by XingZiLong** [comment]
As I don’t want to open another issue I’ll talk about another great idea. Can you bring the compiler to my mobile devices?😄

**Comment by antfu** [comment]
Thanks for the suggestions/ideas!

> As I can’t type ‘云云’ on traditional Chinese keyboard but other keyword ARE traditional characters.

`雲` and `云` are both Traditional Chinese. They just happened to be simplified as a same character `云` in Simplified Chinese. Actually `雲` and `云` have very different meanings, you can refer to http://chardb.iis.sinica.edu.tw/meancompare/96f2/4e91 or just simplily google them.

> I’m also considering about ‘\n’, which is not a Chinese character.

We already have some discussion about it #128 

> Can you bring the compiler to my mobile devices?

The compiler is written in Javascript, which means it can run in any modern browsers(includes mobile devices). You can try our Online IDE in the browser, although the UX for touchscreens is not optimal, and we will definitely impove it in the future.

**Comment by XingZiLong** [comment]
Many thanks to you. I hope you could make \n to Chinese characters soon~
