### ISSUE TITLE
在前一个函数内调用函数时，后一个函数“書之”编译出bug

### ISSUE THREAD

**Issue by akira-cn** [wenyan-lang/wenyan#581]
测试代码：

```
吾有一術。名之曰「倏忽」。欲行是術。必先得一術。曰「籌」。
乃行是術曰。
  施「(x=>setInterval(x, 0))」於「籌」。
是謂「倏忽」之術也。

吾有一術。名之曰「問天地好在」。乃行是術曰。
	吾有一言。曰「「問天地好在。」」。書之。
是謂「問天地好在」之術也。
```

运行环境：

https://wy-lang.org/ide

编译结果如下截图：

![](https://p4.ssl.qhimg.com/t0198b18b0d96f50356.jpg)

**Comment by LingDong-** [comment]
Hi @akira-cn , thanks for bringing this up.

`書之` will print out all unnamed variables. And in your case, `_ans1` is never given a name, hence printed out.

The right way is to use `噫` to flush unnamed variables whenever you do not need the output, like so:

```
乃行是術曰。
  施「(x=>setInterval(x, 0))」於「籌」。噫。
是謂「倏忽」之術也。
```

I agree this is not very intuitive. One way is probably to automatically flush unnamed variables at the end of every scope, now that wenyan-lang is blocked scoped.

**Comment by akira-cn** [comment]
謝謝。

我試著寫了一個新的模塊：

https://github.com/akira-cn/kelou-wy

提交到了文淵閣：

https://github.com/wenyan-lang/wyg-registry/pull/2

**Comment by LingDong-** [comment]
Awesome job! Nice use of classical time-describing words (未几须臾 etc.). Thanks for making this 👏
