### ISSUE TITLE
异常类型与WIKI

### ISSUE THREAD

**Issue by XingZiLong** [wenyan-lang/wenyan#582]
在编写try-catch结构时，一些如‘ReferenceError’ ‘SyntaxError’的名称使得程序很不美观。「算经」缺少「开方」工具，但用「Math.sqrt」同样也打破了文言的简洁。希望可以把文言化作彻底一些。还有就是希望Wiki中能有教程，一些例如「混沌」「画经」之类的刚开始搞不清楚

**Comment by LingDong-** [comment]
Hi @XingZiLong , thanks for bringing these up.

> ‘ReferenceError’ ‘SyntaxError’

There is indeed a plan to improve this, see: https://github.com/wenyan-lang/wenyan/issues/566#issuecomment-580194266

> 「算经」缺少「开方」工具

Not true :) It is called `「平方根」`. See documentation in [wiki](https://github.com/wenyan-lang/wenyan/wiki/Standard-Library-Cheatsheet#算經---math)


> 还有就是希望Wiki中能有教程，一些例如「混沌」「画经」之类的刚开始搞不清楚

We're working on improving the documentation. Stay tuned :)

**Comment by XingZiLong** [comment]
Thank you there. I’m in China and the outbreak of novel coronaviruses from Wuhan is terrifying. Wish you healthy.望君保重。
