### ISSUE TITLE
文言代碼中嵌入多行的JS代碼

### ISSUE THREAD

**Issue by akira-cn** [wenyan-lang/wenyan#585]
這樣在寫一些複雜的應用的時候，就可以更方便用node模塊和JS的庫。
我現在用了一個 hack 的辦法，不知道這個能否從語言層面上支持一下。

```
或云『吾嘗聞爪哇國有腳本』蓋謂『疏曰*/』
或云『其文如是矣』蓋謂『/*』

吾嘗聞爪哇國有腳本
function f1() {
  return "f1";
}
function f2() {
  return "f2";
}
其文如是矣。

施「f1」。書之。
施「f2」。書之。
```

編譯後：

```js
/**/
function f1() {
    return "f1";
}

function f2() {
    return "f2";
}
/*。

*/
const _ans1 = f1();
console.log(_ans1);
const _ans2 = f2();
console.log(_ans2);
```

**Comment by antfu** [comment]
Nice hack 😆👍 As you are able to do in marco (and looks pretty elegant), I think it's better to an optional package instead of the language itself for now. Would love to see it available in wyg :) Thanks.

**Comment by antfu** [comment]
The package is published in [wyg](https://wyg.wy-lang.org/) called `腳本秘術`. Closing now. Thanks!
