### ISSUE TITLE
Online IDE package info cannot be closed

### ISSUE THREAD

**Issue by Meowcolm024** [wenyan-lang/wenyan#588]
I'v tried it on Safari and Chrome, but neither worked. I don't whether it's a problem specific to me...

<img width="1450" alt="截圖 2020-02-22 下午1 04 49" src="https://user-images.githubusercontent.com/23007687/75086862-ea604880-5573-11ea-8466-d3003c315879.png">

**Comment by LingDong-** [comment]
Now fixed: https://github.com/wenyan-lang/ide/commit/a679dadd65eda28a602598c4d15ad848e4835443

@Meowcolm024, Thanks a lot for reporting the bug!

@antfu, I fixed it with dirty `window.` hack, you might want to redo it properly :)  I think it should be incorporated into`function showPackageInfo(pkg)`, if that sounds right I can do it.

**Comment by antfu** [comment]
Thanks for the fix. I think the window. is an ok way to do this, it supposed to be exposed to the window. I wrapped the script in an instant executing function to handle the async/await. No need for further change currently I suppose :)
