### ISSUE TITLE
编译成 JS 或 Python 不用把标识符转为拼音

### ISSUE THREAD

**Issue by nobodxbodon** [wenyan-lang/wenyan#59]
编译后可以继续用中文标识符。毕竟[它们都支持中文命名](https://github.com/program-in-chinese/team_website/blob/master/_posts/2017-10-23-%E5%9C%A8%E5%90%84%E7%A7%8D%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%B8%AD%E6%96%87%E5%91%BD%E5%90%8D.markdown)。
这样还可以避免标识符的拼音相重的问题。

**Comment by jiangzoi** [comment]
這個建議不錯，會在之後版本中考慮。

**Comment by LingDong-** [comment]
@jiangzoi, not exactly. 
1. I just fixed it and committed. Now all the original identifiers are used by default. (with an option to use unicode entry point or pinyin)
2. Please refer to this earlier issue https://github.com/LingDong-/wenyan-lang/issues/6 for detailed discussion on this topic.

**Comment by antfu** [comment]
You can specify the `romanizeIdentifiers` in https://github.com/wenyan-lang/wenyan/wiki/Compiler-API#compiler-options now!
