### ISSUE TITLE
Pattern Matching 

### ISSUE THREAD

**Issue by Meowcolm024** [wenyan-lang/wenyan#599]
I'm thinking about whether this language could also add the feature of pattern matching.

Like in Haskell, we have:

``` haskell
fib :: Int -> Int
fib n = case n of 
  0 -> 0
  1 -> 1
  _ -> fib (n-1) + fib (n-2)
```

maybe in Wenyan we can have a similar one like:

``` 
吾有一術。名之曰「斐波那契」。欲行是術。必先得一數。曰「甲」。乃行是術曰。
    至於「甲」者
    為零者乃得零也
    為一者乃得一也
    非者  -- I suppose we shall have a more complex syntax to achieve `fib (n-1) + fib (n-2)`
是謂「斐波那契」之術也。
```

However, matching lists like `[_, _, _]` may be too complicated to achieve in a non functional language.

**Comment by Meowcolm024** [comment]
I suppose it is duplicated:(

**Comment by LingDong-** [comment]
Good proposal actually, we will consider ;)
