### ISSUE TITLE
[Help wanted]返回减少了一个参数的等效函数

### ISSUE THREAD

**Issue by GLanguage** [wenyan-lang/wenyan#600]
最近给wenyan写class package的时候遇到了严重问题，需求是这样的：
现在有一个術`「甲」`，其参数的数量大于等于1，且第一个参数`「参一」`是确定的（已知的），需要通过某种方法，在不执行術`「甲」`的情况下，得到另一个術`「乙」`，使得`施「甲」於「参一」[於「某」[ ... ]]`的效果和`施「乙」[於「某」[ ... ]]`完全相同（即，将已知的参数从函数的参数列表中去掉）。如果有哪位大佬想出了能实现此的方法，请告诉我，谢谢。
这里列举一些失败的尝试，以免大家走弯路（为了避免一直使用繁体字并且在输入法之间疯狂切换，以下代码会以等效javascript的形式呈现）：
# 低级尝试
由于wenyan是以`f(a)(b)( ... )`的形式定义函数的，即
```
var f = function(a) {
    return function(b) {
        ...
    }
}
```
所以很容易想到`f(a)`就可以得到一个函数`function(b) { ... }`满足`「乙」`的要求。但是，如果`f`只有一个参数，那么
```
var f = function(a) {
    ...
    return xxx;
}
```
此时，如果仍然调用`f(a)`，就会得到`xxx`（如果没有`return`那么就会得到`undefined`），并非一个函数。比如，
```
var sayname = function(self) {
    console.log(self.name);
}
```
这时候，我们调用`sayname(self)`，不仅不会得到什么函数，还会输出`self.name`，即直接执行了整个函数。
殆矣。

# 高级尝试
在低级尝试中，我们发现最大的问题就是当函数参数数量为一的时候不好处理，那么我们只需要在代码中加一个特判就好了：
```
// a is the known argument.
var g = f(a);
if ((typeof g) === "function") {
    // f has more than 1 arguments.
    /* do sth with g */
} else {
    // f has only 1 argument, and it is known.
    var g = function() {
        return f(a);
    }
    /* do sth with g */
}
```
但是，注意这句：
```
var g = f(a);
```
如果`f(a)`只有`a`这一个参数，那么这句仍然会调用函数本身。虽然在后面的判断中，我们能保证最终的`g`一定是个函数，但是在这个过程中调用了函数本身。在这个例子中
```
var sayname = function(self) {
    console.log(self.name);
}
```
虽然可以保证最终一定能得到一个符合条件的函数，但是在得到该函数的过程中，仍然会输出`self.name`。

> 不仅不会得到什么函数，还会输出`self.name`

高级尝试只解决了前者，却没有解决后者。所以在需求中加上了一条：

> 在不执行術`「甲」`的情况下，

殆矣。
# 结尾
实在是太不容易了！这个东西搅得我几天不得安宁，如果有大佬能想出方法的话，请务必告诉我，谢谢。

**Comment by Meowcolm024** [comment]
不是很理解，姑且乱说一下。可以考虑将一个参数的函数变成两个参数的函数

``` python
f = lambda x: lambda: x + 1
```

这样当调用`f`的时候：

``` python
# for `f`
<function <lambda> at 0x10318cc80>
# for `f(1)`
<function <lambda>.<locals>.<lambda> at 0x1031b0730>
# for f(1)()
2
```

假如我们让`g = f(1)`:

然后调用`g`

``` python
# use `g()`
2
```

就相当于是一个有默认参数的无参数的函数了:)

**Comment by GLanguage** [comment]
天呐这个方法也是一个失败的例子（很抱歉一上来就打击了你），因为不太好理解所以没放在失败清单上。
是这样，你的意思在js里大概是：
```
var f = function(a) {
    return function() {
        ...
    }
}
```
However, 
1. 我们在讨论wenyan，wenyan要想这样定义函数，首先得支持匿名函数（其实可以，`施「」於「(function() { ... })」`，但这种方法太投机取巧了）。
2. 为了考虑兼容性，如果对于`f(a)`这样的函数写成`f(a)()`的话，那么函数`h(a)(b)`也得写成`h(a)(b)()`。你定义`g = f(a)`，调用的时候可以`g()`，但是你要是定义`i = h(a)`，调用的时候就得`i(b)()`，多了一个括号。先不考虑wenyan能否实现（其实可以，用`於「」`就行），如果你是使用者，所有没参数的函数（指的是除了已确定的那个参数以外没有参数了）都写成`施「g」`，其他函数都写成`施「i」於「a」於「」`，你肯定不乐意（对使用者要求太高了）。

其实，导致你的绝佳方法无法使用的罪魁祸首是wenyan的函数调用机制。在wenyan中，如果`施`后面没有`於`，那么编译器会自动在函数名后面加一个空括号`()`；如果`施`后面有`於`，那么编译器就不会添加空括号，只会把`於`后面的内容放入括号。这样的机制在大多数情况下都是一种优势，但是在我这种极端需求之下却成了弊端。这也是导致这个需求如此难以实现的原因之一。
P.S. 如果所有的函数调用时后面都不用加`於「」`，那自然很好； 如果所有的函数调用时后面都要加`於「」`，那么我们用一个宏就可以解决（使代码可读性更好）；可是如果一些函数后面要加，一些又不要加，事情就变得……

**Comment by XingZiLong** [comment]
你可以定义一个编译为『於「」』的宏啊

**Comment by XingZiLong** [comment]
而且你可以先就这么写着，再用宏整体代换掉，谁也不会去纠结源码啊

**Comment by GLanguage** [comment]
你可能没太明白我的意思，我是说在只有一个已知参数的情况下不用加`於「」`，但是在参数多于一个的情况下要加`於「」`，如果我们能够在源代码中判断参数数量，那么就可以仿照高级尝试中的做法实现这个需求了呀，问题是不行（如果你可以的话请务必告诉我），所以必须由user自己判断这个函数是否包含多于一个参数，如果包含多于一个参数，那么调用的时候就必须加上`於「」`，无论user加的是`於「」`还是我们定义的宏，都还是得加啊。而且，这样做的话就必须要求user在每一个函数里都加上一层匿名函数。
这种方法有一个变种，可以要求user在所有的只包含一个（已知）参数的函数中都加上一层匿名函数，在所有多于一个参数的函数中都不加，这样在调用的时候既可以一视同仁了，比较爽。但是，user还是必须得在定义的时候进行人工判断。
总之，无论是在调用时还是在定义时，user总要人工判断一次“某函数包含多少个参数”。

**Comment by Meowcolm024** [comment]
其实我想知道为什么不能将`f(a)`写成`f(a)()`，而`f(a)(b)`则保持原样orz
还是这是一个 compiler work ...

**Comment by GLanguage** [comment]
因为`f(a)(b)`直接得到返回值，所以`f(a)`也理应直接得到返回值，可是`f(a)()`的话相当于`f(a)`是函数啊。

**Comment by GLanguage** [comment]
主要是为了elegant

**Comment by XingZiLong** [comment]
js函数里面有一个array型参数arguments，用.length不就可以了

**Comment by XingZiLong** [comment]
哦！我好像搞错了，那个好像不适用于柯里化的函数吧？sorry

**Comment by XingZiLong** [comment]
麻烦一点的思路：把柯里化的函数先转成非柯里化函数 ```f0(?, ?, ?, ..., ?,)``` 再用arguments.length检测

**Comment by GLanguage** [comment]
具体怎样转化？麻烦告诉我谢谢。

**Comment by XingZiLong** [comment]
这个一时半会说不完，查一下‘反柯里化’，网上应该会有

**Comment by XingZiLong** [comment]
// 反柯里化通用式 ES6functionuncurring(fn){returnfunction(...args){return fn.call(...args);}}


这是我在网上复制的，看看有没有一点帮助

**Comment by GLanguage** [comment]
Thanks a lot! 我感觉胜利的曙光*又*不远了

**Comment by XingZiLong** [comment]
。。。**又** 不远了。。。

**Comment by GLanguage** [comment]
的确是「殆矣」了。当然这并不影响class的正常发布。

# 无尽的摸索
@SketchySketch 反柯里化的方法我试过了，不行。主要是因为：
```javascript
var uncurrying = function(fn) {
    return function(...args) {
        return fn.apply(this, args);
    }
}
```
这里`...args`表示可变参数，`args`是参数列表，`args`的长度只有在运行时才能知道；而函数的`length`属性是指必需参数的数量，即可变参数之前的参数的数量，也就是`...args`之前的参数数量，在这里显然为0。
那么为什么我们试了这么多方法却无一成功呢？因为我的需求在js中就是不可实现的。js不可能在「不执行」一个柯里化函数的情况下得知该柯里化函数的参数数量，因为这正是柯里化函数的特点：“参数的局域性”，即参数数量的不可知性。

# An Alternative
当然class support这种重要的东西绝不能因为这样一点小事就失败，我想到了一个可行办法。
@Meowcolm024 曾经提过的那个办法其实可以实施，只是不太...elegant。我之前提过，我们只需将所有的`f(self)`都改为`f(self)()`，而其他的`g(self)(a)`都不变，那么我们调用`f(self)`就能得到`function()`，调用`g(self)`就能得到`function(a)`，只不过需要让使用者自己判断罢了。其实有一个办法，
```
或云「「無余參矣」」。
蓋謂「「一元。曰「」。」」。
```
然后，
```
吾有一術。名之曰「報名」。欲行是術。必先得一物。曰「己」。無余參矣。乃行是術曰。
    夫「己」。夫「「名」」。取二以施「取物」。加其於「「吾乃」」。加其以「「也。」」。書之。
是謂「報名」之術也。
```
就能实现我刚刚说的`f(self)()`，这样对使用者也不是特别不友好。在使用的时候，如果发现一个方法除了`「己」`参数以外没有其他参数了，那么就在后面加一个`無余參矣`，就能实现
```javascript
var f = function(self) {
    return function() {
        ...
    }
}
```
如果后面还有其他的参数，就不加`無余參矣`。
虽然说`一元。曰「」。`有点hack，但是只要用一个宏封装起来就没事了。有点像`施「」於「function() { ... }」`。:)
代码我已经调试过了，全部测试都通过了。不过实践出真知，我把它放到`wyg`上，看看会不会有什么隐藏bug吧。:P
我要close了，再见！
