### ISSUE TITLE
Don’t output anything

### ISSUE THREAD

**Issue by SketchySketch** [wenyan-lang/wenyan#606]
Hello, I just install your wenyan client by NPM latest version, and run the code below:
```
吾有一言。曰『問天地好在』。書之。
```
By using command:
```
wenyan <path>
```
I am sure that the path is right. But why it doesn’t out put anything?
:ADDITIONAL INFORMATION: PC version Windows 7, x64:

**Comment by SketchySketch** [comment]
The worst thing is that it doesn’t even report an exception or an error! It looks like this:
```
C:\> wenyan C:\Users\administrator\desktop\wenyan\try.wy

C:\>
```
#### ?????

**Comment by antfu** [comment]
Hi @SketchySketch, what the output for `wanyan -v`.

It works for me
```bash
➜  ~ wenyan -v
0.3.2
➜  ~ wenyan ./Github/wenyan/examples/helloworld.wy
問天地好在。
➜  ~
```

**Comment by SketchySketch** [comment]
Also my output of wenyan -v is 0.3.2

**Comment by SketchySketch** [comment]
Is it that my PC version is not compatible? Can I download node.js 12.x on Windows 7?
And a small detail is, when I install the client, node.js has thrown an error. I don’t mention it much, but it is something like
```
npm WARN ET… (I forget, sorry)
```

**Comment by antfu** [comment]
Can you try to install it again and see if the error still preserves? Otherwise I am doubting that would be something to do with Windows. (I don't have access to a windows now but I would try it later)

**Comment by SketchySketch** [comment]
I have just found a clue to the problem: I
 rendered the program, and it just give me lots of unrecognizable characters. So I think it would be that my encoding is not compatible.
So, which encoding is available? I am using SOGO. 
By the way, how can I type the quotes?

**Comment by antfu** [comment]
We use utf-8. Please check your editor settings.

For the quotes, you can try the online IDE or the VSCode extension. Both of them will convert english symbols to Chinese ones.

https://ide.wy-lang.org/
https://github.com/antfu/wenyan-lang-vscode

**Comment by SketchySketch** [comment]
I installed the extension and I was right. When I open the file it is not encoded correctly. Thanks for your help.
