### ISSUE TITLE
为啥花这么大精力去做这么愚蠢的一个项目

### ISSUE THREAD

**Issue by resir** [wenyan-lang/wenyan#607]

**Comment by TangMonk** [comment]
不为名利，只为有趣。古人云：何以小之心，度君子之腹。古人又云：燕雀安知鸿鹄之志。何必恶语重伤他人？

**Comment by UltraSoundX** [comment]
写程序就像是说话，每个人想说的话自然不一样，你觉着这个项目是废物，那我觉着别人的页面上弄的看板娘也屁用没有，我也不见得去批评别人，每个人想法和层次不一样，你有什么资格去评论别人用心血创作的项目呢？

**Comment by resir** [comment]
> 写程序就像是说话，每个人想说的话自然不一样，你觉着这个项目是废物，那我觉着别人的页面上弄的看板娘也屁用没有，我也不见得去批评别人，每个人想法和层次不一样，你有什么资格去评论别人用心血创作的项目呢？

此言有理， 受教了
