### ISSUE TITLE
众人云：香！ 真香！

### ISSUE THREAD

**Issue by resir** [wenyan-lang/wenyan#608]

**Comment by zrzjohn** [comment]
汝不能言。人家是一种娱也。汝知python何来之乎？一始Guido van Rossum即在1989年圣诞节假闲得无聊时，写出之。万一他日能越矣，亦一善也！

**Comment by SketchySketch** [comment]
汝言之或有理。然出如此惡言，不知汝知所欲言也。汝言此項目『愚蠢』，欲知何處『愚』，何處『蠢』，故可以汝之言改進，何『愚蠢』之有耶？

**Comment by Meowcolm024** [comment]
世间之物，多无用者，然以恶言相向，吾未见其明者。汝之所言无用者，或为功用，英文之utility也。然以功用者判世间万物，则多为无用。鸟兽不啖，无用者也；夫游戏者，多不可明智，无用者也，诸如此者，不可胜数。或汝愚wenyan-lang者，然习编程语言者，学TypeScript者，可以之为经，其为用也。

**Comment by UltraSoundX** [comment]
我不懂文言文，但是我想问问resir，您的jsrun在线编译何用只有？本地编译这么方便，为何要去在线编译乎？

**Comment by wysteven** [comment]
汝之言貽矣，昔之UNIX之創，實為湯普森欲戯之，而初，其系統不盡善，故其創C語言以重寫UNIX。故今世之創新，需人之思矣。《易》云，日新之謂盛德。及今世之況，極欲創新，然今世之創新，未止有用。汝只聞有用之用，未知無用之用也。

**Comment by z-huabao** [comment]
> 汝之言貽矣，昔之UNIX之創，實為湯普森欲戯之，而初，其系統不盡善，故其創C語言以重寫UNIX。故今世之創新，需人之思矣。《易》云，日新之謂盛德。及今世之況，極欲創新，然今世之創新，未止有用。山木自寇也，膏火自煎也。桂可食，故伐之。漆可用，故割之。世人皆知有用之用，而莫知無用之用也。
“世人皆知有用之用，而莫知無用之用也”，说得好！这句话应该放在项目开头，省的这么多无聊之人瞎bb。
