### ISSUE TITLE
[更新请求]网络请求

### ISSUE THREAD

**Issue by purofle** [wenyan-lang/wenyan#612]
是否支持发送websocket/post/get请求？

**Comment by SketchySketch** [comment]
目前应该是不行的。
用JS实现Web请求主要有以下方法：
- jQuery。但是这个项目不是网页，不能直接嵌入。
- Node.js。
  - 使用require('http')。但在wenyan中没有require。
  - 使用module。但在wyg中没有支持此要求的module。

**Comment by purofle** [comment]
> 目前应该是不行的。
> 用JS实现Web请求主要有以下方法：
> 
> * jQuery。但是这个项目不是网页，不能直接嵌入。
> * Node.js。
>   
>   * 使用require('http')。但在wenyan中没有require。
>   * 使用module。但在wyg中没有支持此要求的module。

那么是否可以直接在wyg中使用node函数？

**Comment by SketchySketch** [comment]
我对Node.js不是很了解，但是Node.js好像要用node命令吧
如果是这样，那就是wenyan library的事情了，而不是wyg能搞定的
（至少我猜是这样。。。吧）
