### ISSUE TITLE
Trying to access the book on the wiki doesn't work

### ISSUE THREAD

**Issue by user670** [wenyan-lang/wenyan#615]
https://github.com/wenyan-lang/wenyan/wiki/Book

Trying to access this redirects to https://github.com/wenyan-lang/wenyan/wiki with a message that reads "You do not have permission to update this wiki.".

**Comment by LingDong-** [comment]
Hi, thank you for pointing out, the link in the wiki was a mistake. The correct link to the book is https://github.com/wenyan-lang/book.

I just edited the wiki, should be correct now. Thanks!
