### ISSUE TITLE
“「”和“」”怎么输入？

### ISSUE THREAD

**Issue by Dovuq** [wenyan-lang/wenyan#626]
我只能复制粘贴。。。。。。

**Comment by wglnngt** [comment]
某些系統（如MAC）直接輸入引號可得。WINDOWS下，可開輸入法之軟鍵盤，如百度輸入法，即可以CTRL+SHIFT+K開之，若事先調至中文符號，則可以鍵盤按鍵快速輸入（JKL;四鍵即是）。其它輸入法應有類似功能。
若編輯工俱爲VIM之類，則可利用其宏功能快速錄製插入字符操作。利用宏可能快速彔入此類特殊字符（如以V鍵記錄爲插入「」字符，表示variant，以Q鍵記錄爲插入『』字符，表示quote，則在欲插入字符處按@v,@q即可得相應符號）。

**Comment by Dovuq** [comment]
真麻烦。。。
