### ISSUE TITLE
I have a great idea.

### ISSUE THREAD

**Issue by MaiXiaoMeng** [wenyan-lang/wenyan#67]
Consider adding a feature that converts Python source code into classical Chinese?
Classical Chinese is actually difficult to understand, haha

**Comment by LingDong-** [comment]
Great idea indeed! Would require a lot of work to implement though, see also https://github.com/LingDong-/wenyan-lang/issues/47 for the discussion.
Thanks.

**Comment by luxiuyuan2013** [comment]
#617  oh
