### ISSUE TITLE
嗨，大家好！ 我是来自俄罗斯的学生，我想给我的编程老师一个惊喜！----Hi guys! I am a student from Russia and I want to surprise my programming teacher a little!----Привет, ребята! Я студент из России и хочу немного удивить своего преподавателя по программированию!

### ISSUE THREAD

**Issue by AliyAcho** [wenyan-lang/wenyan#671]
问题是我根本不懂你的语言。 所以我看不懂这种奇妙的编程语言（wenyang lang）。 你可能不相信，但我的编程老师真的让我不用任何编程语言完成作业。 我用 Python3.8 写了代码，如果能在 wenyan-lang 中看到它会很高兴！！！ 谢谢！
---
The problem is that I don't understand your language at all. So I don't understand this wonderful programming language (wenyang lang). You may not believe it, but my programming teacher really allowed me to complete the assignments not in any programming language. I wrote the code in Python3.8 and it would be nice to see it in wenyan-lang!!! Thanks!
---
Проблема в том, что я вообще не понимаю ваш язык. А значит я не понимаю и этот прекрасный язык программирования(wenyang lang). Вы можете не верить, но мой преподаватель по программированию действительно разрешил выполнить задания не любом языке программирования. Я написал код на Python3.8, и было бы неплохо увидеть его на wenyan-lang!!! Спасибо!
---
CODE:
`
hash_table = [0] * 300 # массив для записи идентификаторов
hash_index = [0] * 300 # массив для записи индексов идентификаторов
i = 0

file1 = open("text.txt","r")

with open('text.txt') as openfileobject:
    for word in openfileobject:
        print(word[0:-1])
        index = ord(word[0]) + ord(word[-1])
        while hash_table[index] != 0:
            index += 1
            index = index % 301
        else:
            hash_table[index] = word
            hash_index[i] = index
        i += 1
`

**Comment by nobodxbodon** [comment]
There's a tool to convert JS to wenyan: https://github.com/zxch3n/wenyanizer
Not sure if there's similar tool for Python.

**Comment by AliyAcho** [comment]
Thanks! I think he will be a little surprised!
