### ISSUE TITLE
希望能增加JS/python/c程序编译成文言文的功能

### ISSUE THREAD

**Issue by Tairraos** [wenyan-lang/wenyan#73]
希望能增加JS/python/c程序编译成文言文的功能

**Comment by cbfrank** [comment]
确实，如果直接用文言写还是有点累，如果能直接从JS代码转译就很方便了

**Comment by jeffli678** [comment]
先从c到LLVM，然后而emscripten到js。js应该能比较容易的转换成wenyan

**Comment by ylvict** [comment]
Reference to: https://github.com/LingDong-/wenyan-lang/issues/67

**Comment by BlankRain** [comment]
antlr4 了解一下...

**Comment by antfu** [comment]
There is a project [wenyanizer](https://github.com/zxch3n/wenyanizer) by @zxch3n allowing you to compile JS to wenyan now.
